# Generated by Django 6.0.4 on 2026-05-06 09:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_tenantbranding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileResource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('branding', 'Branding White-Label'), ('user_profile', 'Perfil de Usuario'), ('user_document', 'Documento de Usuario'), ('customer_document', 'Documento de Cliente'), ('loan_application', 'Solicitud de Crédito'), ('loan_contract', 'Contrato de Crédito'), ('payment_receipt', 'Comprobante de Pago'), ('identity_document', 'Documento de Identidad'), ('income_proof', 'Comprobante de Ingresos'), ('collateral', 'Garantía'), ('backup', 'Respaldo'), ('export', 'Exportación'), ('report', 'Reporte')], db_index=True, max_length=30, verbose_name='Tipo de Recurso')),
                ('entity_type', models.CharField(blank=True, help_text='Ejemplo: tenant_branding, user, customer, loan', max_length=50, verbose_name='Tipo de Entidad')),
                ('entity_id', models.UUIDField(blank=True, help_text='UUID de la entidad relacionada', null=True, verbose_name='ID de Entidad')),
                ('original_name', models.CharField(help_text='Nombre del archivo subido por el usuario', max_length=255, verbose_name='Nombre Original')),
                ('stored_name', models.CharField(help_text='Nombre único generado (UUID)', max_length=255, unique=True, verbose_name='Nombre Almacenado')),
                ('file_path', models.CharField(help_text='Ruta completa en Supabase Storage', max_length=500, unique=True, verbose_name='Ruta en Storage')),
                ('bucket', models.CharField(default='uploads', max_length=100, verbose_name='Bucket')),
                ('mime_type', models.CharField(help_text='Tipo MIME real del archivo', max_length=100, verbose_name='Tipo MIME')),
                ('extension', models.CharField(help_text='Extensión del archivo sin punto', max_length=20, verbose_name='Extensión')),
                ('size', models.BigIntegerField(help_text='Tamaño del archivo en bytes', verbose_name='Tamaño (bytes)')),
                ('category', models.CharField(blank=True, db_index=True, help_text='Subcategoría del recurso: logo, favicon, cover, identity, contract, etc.', max_length=50, verbose_name='Categoría')),
                ('visibility', models.CharField(choices=[('private', 'Privado (requiere signed URL)'), ('public', 'Público'), ('tenant_only', 'Solo miembros del tenant')], default='private', max_length=20, verbose_name='Visibilidad')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('replaced', 'Reemplazado'), ('deleted', 'Eliminado'), ('orphaned', 'Huérfano')], db_index=True, default='active', max_length=20, verbose_name='Estado')),
                ('checksum', models.CharField(blank=True, help_text='Hash SHA-256 del archivo para verificar integridad', max_length=64, verbose_name='Checksum SHA-256')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadata adicional en formato JSON', verbose_name='Metadata Adicional')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_history', to='storage.fileresource', verbose_name='Reemplazado por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_resources', to='tenants.financialinstitution', verbose_name='Tenant')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Recurso de Archivo',
                'verbose_name_plural': 'Recursos de Archivos',
                'db_table': 'file_resources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('upload', 'Subida'), ('download', 'Descarga'), ('delete', 'Eliminación'), ('replace', 'Reemplazo'), ('view', 'Visualización')], max_length=20, verbose_name='Acción')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('file_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='storage.fileresource', verbose_name='Archivo')),
            ],
            options={
                'verbose_name': 'Log de Acceso a Archivo',
                'verbose_name_plural': 'Logs de Acceso a Archivos',
                'db_table': 'file_access_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='fileresource',
            index=models.Index(fields=['tenant', 'resource_type'], name='file_resour_tenant__9ccbf1_idx'),
        ),
        migrations.AddIndex(
            model_name='fileresource',
            index=models.Index(fields=['tenant', 'status'], name='file_resour_tenant__9d6414_idx'),
        ),
        migrations.AddIndex(
            model_name='fileresource',
            index=models.Index(fields=['entity_type', 'entity_id'], name='file_resour_entity__c8ba69_idx'),
        ),
        migrations.AddIndex(
            model_name='fileresource',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='file_resour_uploade_0c058f_idx'),
        ),
        migrations.AddIndex(
            model_name='fileresource',
            index=models.Index(fields=['category'], name='file_resour_categor_c58eaf_idx'),
        ),
        migrations.AddConstraint(
            model_name='fileresource',
            constraint=models.CheckConstraint(condition=models.Q(('size__gte', 0)), name='file_resource_size_positive'),
        ),
        migrations.AddIndex(
            model_name='fileaccesslog',
            index=models.Index(fields=['file_resource', 'created_at'], name='file_access_file_re_faa0b5_idx'),
        ),
        migrations.AddIndex(
            model_name='fileaccesslog',
            index=models.Index(fields=['user', 'action'], name='file_access_user_id_a47a58_idx'),
        ),
    ]
