# Generated by Django 6.0.4 on 2026-05-10 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_create_file_resource_model'),
        ('tenants', '0003_create_file_resource_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceReportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('TENANT', 'Tenant'), ('SAAS', 'SaaS')], max_length=10, verbose_name='Scope')),
                ('audio_duration_seconds', models.IntegerField(default=0, verbose_name='Duración de Audio (seg)')),
                ('transcription', models.TextField(blank=True, help_text='Texto transcrito del audio', null=True, verbose_name='Transcripción')),
                ('transcription_language', models.CharField(blank=True, max_length=10, null=True, verbose_name='Idioma de Transcripción')),
                ('parsed_intent_json', models.JSONField(blank=True, help_text='Intención interpretada por IA en formato JSON', null=True, verbose_name='Intención Parseada JSON')),
                ('validation_status', models.CharField(choices=[('VALID', 'Válido'), ('NEEDS_REVIEW', 'Necesita Revisión'), ('INVALID', 'Inválido')], default='NEEDS_REVIEW', max_length=20, verbose_name='Estado de Validación')),
                ('missing_fields_json', models.JSONField(blank=True, help_text='Lista de campos faltantes en la configuración', null=True, verbose_name='Campos Faltantes JSON')),
                ('unsupported_terms_json', models.JSONField(blank=True, help_text='Lista de términos no soportados detectados', null=True, verbose_name='Términos No Soportados JSON')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
                ('groq_transcription_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo de Transcripción Groq')),
                ('groq_chat_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo de Chat Groq')),
                ('processing_time_seconds', models.IntegerField(default=0, verbose_name='Tiempo de Procesamiento (seg)')),
                ('audio_file_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_report_requests', to='storage.fileresource', verbose_name='Archivo de Audio')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_report_requests', to='tenants.financialinstitution', verbose_name='Institución')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voice_report_requests', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Solicitud de Reporte por Voz',
                'verbose_name_plural': 'Solicitudes de Reportes por Voz',
                'db_table': 'reports_voice_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('TENANT', 'Tenant'), ('SAAS', 'SaaS')], max_length=10, verbose_name='Scope')),
                ('category', models.CharField(max_length=50, verbose_name='Categoría')),
                ('report_type', models.CharField(max_length=100, verbose_name='Tipo de Reporte')),
                ('config_json', models.JSONField(help_text='Configuración completa del reporte', verbose_name='Configuración JSON')),
                ('generation_source', models.CharField(choices=[('MANUAL', 'Manual'), ('AUDIO', 'Audio')], default='MANUAL', max_length=10, verbose_name='Fuente de Generación')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX')], max_length=10, verbose_name='Formato de Archivo')),
                ('row_count', models.IntegerField(blank=True, help_text='Número de filas en el reporte', null=True, verbose_name='Cantidad de Filas')),
                ('processing_time_seconds', models.IntegerField(blank=True, help_text='Tiempo que tomó generar el reporte', null=True, verbose_name='Tiempo de Procesamiento (seg)')),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si la generación falló', null=True, verbose_name='Mensaje de Error')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado en')),
                ('file_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='storage.fileresource', verbose_name='Archivo')),
                ('institution', models.ForeignKey(blank=True, help_text='Institución financiera. Null para reportes SAAS.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='tenants.financialinstitution', verbose_name='Institución')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_reports', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('voice_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='reports.voicereportrequest', verbose_name='Solicitud de Voz')),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'verbose_name_plural': 'Reportes Generados',
                'db_table': 'reports_generated',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('TENANT', 'Tenant'), ('SAAS', 'SaaS')], help_text='Alcance del reporte: TENANT o SAAS', max_length=10, verbose_name='Scope')),
                ('category', models.CharField(help_text='Categoría del reporte (CREDITS, CUSTOMERS, etc.)', max_length=50, verbose_name='Categoría')),
                ('report_type', models.CharField(help_text='Tipo específico de reporte según catálogo', max_length=100, verbose_name='Tipo de Reporte')),
                ('name', models.CharField(help_text='Nombre descriptivo de la plantilla', max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, help_text='Descripción opcional de la plantilla', null=True, verbose_name='Descripción')),
                ('config_json', models.JSONField(help_text='Configuración completa del reporte en formato JSON', verbose_name='Configuración JSON')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la plantilla está activa', verbose_name='Activo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_report_templates', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('institution', models.ForeignKey(blank=True, help_text='Institución financiera. Null para reportes SAAS.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='tenants.financialinstitution', verbose_name='Institución')),
            ],
            options={
                'verbose_name': 'Plantilla de Reporte',
                'verbose_name_plural': 'Plantillas de Reportes',
                'db_table': 'reports_template',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['institution', 'scope', 'category'], name='reports_tem_institu_c5b7a2_idx'), models.Index(fields=['created_by', 'is_active'], name='reports_tem_created_27368f_idx'), models.Index(fields=['scope', 'category', 'report_type'], name='reports_tem_scope_238beb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='voicereportrequest',
            index=models.Index(fields=['institution', 'validation_status'], name='reports_voi_institu_f0ad87_idx'),
        ),
        migrations.AddIndex(
            model_name='voicereportrequest',
            index=models.Index(fields=['requested_by', 'created_at'], name='reports_voi_request_763e46_idx'),
        ),
        migrations.AddIndex(
            model_name='voicereportrequest',
            index=models.Index(fields=['validation_status', 'created_at'], name='reports_voi_validat_46fe56_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['institution', 'scope', 'status'], name='reports_gen_institu_d4be0c_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['requested_by', 'created_at'], name='reports_gen_request_d14d80_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['status', 'created_at'], name='reports_gen_status_bad7ba_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['generation_source', 'status'], name='reports_gen_generat_c323d0_idx'),
        ),
    ]
