# Generated by Django 4.2 on 2026-05-10

from django.db import migrations


def create_report_permissions(apps, schema_editor):
    """Crea permisos personalizados para reportes."""
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    # Obtener content type para reportes
    try:
        report_ct = ContentType.objects.get(app_label='reports', model='generatedreport')
    except ContentType.DoesNotExist:
        # Si no existe, crearlo
        report_ct = ContentType.objects.create(
            app_label='reports',
            model='generatedreport'
        )
    
    # Permisos a crear
    permissions = [
        ('view_report_catalog', 'Can view report catalog'),
        ('generate_report', 'Can generate reports'),
        ('export_report', 'Can export reports'),
        ('manage_templates', 'Can manage report templates'),
        ('use_voice_reports', 'Can use voice reports'),
        ('view_all_reports', 'Can view all reports in tenant'),
        ('access_saas_reports', 'Can access SAAS reports'),
        ('access_tenant_reports', 'Can access TENANT reports'),
    ]
    
    for codename, name in permissions:
        Permission.objects.get_or_create(
            codename=codename,
            content_type=report_ct,
            defaults={'name': name}
        )


def reverse_permissions(apps, schema_editor):
    """Elimina permisos personalizados."""
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    try:
        report_ct = ContentType.objects.get(app_label='reports', model='generatedreport')
        Permission.objects.filter(
            content_type=report_ct,
            codename__in=[
                'view_report_catalog',
                'generate_report',
                'export_report',
                'manage_templates',
                'use_voice_reports',
                'view_all_reports',
                'access_saas_reports',
                'access_tenant_reports',
            ]
        ).delete()
    except ContentType.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RunPython(create_report_permissions, reverse_permissions),
    ]
