# Generated by Django 4.2 on 2026-05-10

from django.db import migrations


def assign_permissions_to_roles(apps, schema_editor):
    """Asigna permisos de reportes a roles existentes."""
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    try:
        report_ct = ContentType.objects.get(app_label='reports', model='generatedreport')
    except ContentType.DoesNotExist:
        return
    
    # Permisos por rol
    role_permissions = {
        'ADMIN': [
            'view_report_catalog',
            'generate_report',
            'export_report',
            'manage_templates',
            'use_voice_reports',
            'view_all_reports',
            'access_saas_reports',
            'access_tenant_reports',
        ],
        'MANAGER': [
            'view_report_catalog',
            'generate_report',
            'export_report',
            'manage_templates',
            'use_voice_reports',
            'view_all_reports',
            'access_tenant_reports',
        ],
        'ANALYST': [
            'view_report_catalog',
            'generate_report',
            'export_report',
            'use_voice_reports',
            'access_tenant_reports',
        ],
        'OFFICER': [
            'view_report_catalog',
            'generate_report',
            'export_report',
            'access_tenant_reports',
        ],
    }
    
    for role_name, permission_codenames in role_permissions.items():
        # Obtener o crear grupo
        group, created = Group.objects.get_or_create(name=role_name)
        
        # Asignar permisos
        for codename in permission_codenames:
            try:
                permission = Permission.objects.get(
                    codename=codename,
                    content_type=report_ct
                )
                group.permissions.add(permission)
            except Permission.DoesNotExist:
                pass


def reverse_permissions_assignment(apps, schema_editor):
    """Remueve permisos de reportes de roles."""
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    try:
        report_ct = ContentType.objects.get(app_label='reports', model='generatedreport')
        permissions = Permission.objects.filter(content_type=report_ct)
        
        for group in Group.objects.all():
            group.permissions.remove(*permissions)
    except ContentType.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_add_permissions'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(assign_permissions_to_roles, reverse_permissions_assignment),
    ]
