# Generated by Django 6.0.4 on 2026-05-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_assign_permissions_to_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedreport',
            name='file_size_bytes',
            field=models.BigIntegerField(blank=True, help_text='Tamaño del archivo generado en bytes', null=True, verbose_name='Tamaño de Archivo (bytes)'),
        ),
    ]
