# Generated by Django 6.0.2 on 2026-06-20 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_create_file_resource_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('MORA_ALERT', 'Alerta de Mora'), ('PAYMENT_REMINDER', 'Recordatorio de Pago'), ('STATUS_CHANGE', 'Cambio de Estado'), ('NEW_MESSAGE', 'Nuevo Mensaje'), ('SYSTEM', 'Sistema'), ('MARKETING', 'Marketing'), ('GENERAL', 'General')], default='GENERAL', max_length=20, verbose_name='Tipo de Notificación')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('body', models.TextField(verbose_name='Cuerpo')),
                ('data_json', models.JSONField(blank=True, default=dict, verbose_name='Datos Adicionales')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL de Imagen')),
                ('click_action', models.CharField(blank=True, help_text='Ruta o deep link a abrir cuando se toca la notificación', max_length=200, null=True, verbose_name='Acción al Hacer Click')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Lectura')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Enviada')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fallo')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
                ('sent_via', models.CharField(blank=True, choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web')], max_length=10, null=True, verbose_name='Enviada Via')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'), models.Index(fields=['is_sent'], name='notificatio_is_sent_254da2_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Código único para identificar la plantilla', max_length=50, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('notification_type', models.CharField(choices=[('MORA_ALERT', 'Alerta de Mora'), ('PAYMENT_REMINDER', 'Recordatorio de Pago'), ('STATUS_CHANGE', 'Cambio de Estado'), ('NEW_MESSAGE', 'Nuevo Mensaje'), ('SYSTEM', 'Sistema'), ('MARKETING', 'Marketing'), ('GENERAL', 'General')], default='GENERAL', max_length=20, verbose_name='Tipo de Notificación')),
                ('title_template', models.CharField(help_text='Título de la notificación. Usar {{variable}} para parámetros.', max_length=200, verbose_name='Título')),
                ('body_template', models.TextField(help_text='Cuerpo de la notificación. Usar {{variable}} para parámetros.', verbose_name='Cuerpo')),
                ('data_json', models.JSONField(blank=True, default=dict, help_text='Datos adicionales en formato JSON para enviar con la notificación', verbose_name='Datos Adicionales')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_templates_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
            ],
            options={
                'verbose_name': 'Plantilla de Notificación',
                'verbose_name_plural': 'Plantillas de Notificaciones',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='notificatio_code_ffac41_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_d9e94e_idx'), models.Index(fields=['is_active'], name='notificatio_is_acti_b2a982_idx')],
                'constraints': [models.UniqueConstraint(fields=('institution', 'code'), name='unique_template_code_per_institution')],
            },
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(help_text='Token de Firebase Cloud Messaging', max_length=500, verbose_name='FCM Token')),
                ('device_type', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web')], default='ANDROID', max_length=10, verbose_name='Tipo de Dispositivo')),
                ('device_name', models.CharField(blank=True, help_text='Ej: iPhone 15, Chrome on Windows', max_length=100, null=True, verbose_name='Nombre del Dispositivo')),
                ('device_id', models.CharField(blank=True, help_text='Identificador único del dispositivo', max_length=100, null=True, verbose_name='ID del Dispositivo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Último Uso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Token Push',
                'verbose_name_plural': 'Tokens Push',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='notificatio_user_id_47d48f_idx'), models.Index(fields=['token'], name='notificatio_token_454efe_idx'), models.Index(fields=['device_type'], name='notificatio_device__67cfdc_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('token',), name='unique_active_token')],
            },
        ),
    ]
