# Generated by Django 6.0.3 on 2026-03-29 00:00
# Parte erick sprint 0

import django.db.models.deletion
from django.db import migrations, models


def seed_permissions(apps, schema_editor):
    Permission = apps.get_model('api', 'Permission')

    default_permissions = [
        {
            'code': 'users.view',
            'name': 'Ver usuarios',
            'description': 'Permite consultar el listado y detalle de usuarios.',
        },
        {
            'code': 'users.create',
            'name': 'Crear usuarios',
            'description': 'Permite registrar nuevos usuarios en el sistema.',
        },
        {
            'code': 'users.edit',
            'name': 'Editar usuarios',
            'description': 'Permite actualizar la informacion de usuarios existentes.',
        },
        {
            'code': 'users.deactivate',
            'name': 'Desactivar usuarios',
            'description': 'Permite desactivar usuarios sin eliminarlos fisicamente.',
        },
        {
            'code': 'roles.manage',
            'name': 'Gestionar roles',
            'description': 'Permite crear, editar y desactivar roles dentro de la entidad.',
        },
    ]

    for permission_data in default_permissions:
        Permission.objects.update_or_create(
            code=permission_data['code'],
            defaults={
                'name': permission_data['name'],
                'description': permission_data['description'],
                'is_active': True,
            },
        )


def unseed_permissions(apps, schema_editor):
    Permission = apps.get_model('api', 'Permission')
    Permission.objects.filter(code__in=['users.view', 'users.create', 'users.edit', 'users.deactivate', 'roles.manage']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'permissions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.financialinstitution')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='api.permission')),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('institution', 'name'), name='uniq_role_name_per_institution')],
            },
        ),
        migrations.RunPython(seed_permissions, unseed_permissions),
    ]
