# Generated by Django 6.0.3 on 2026-03-29 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_twofactorauth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('purpose', models.CharField(default='2fa_login', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('institution_id', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_challenges',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['challenge_token', 'is_used'], name='auth_challe_challen_7b3ec5_idx'), models.Index(fields=['user', 'is_used', 'expires_at'], name='auth_challe_user_id_ab019e_idx')],
            },
        ),
    ]
