# Generated by Django 6.0.3 on 2026-03-29 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_authchallenge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactorauth',
            name='method',
            field=models.CharField(choices=[('totp', 'App Autenticadora'), ('email', 'Código por Email')], default='totp', max_length=20),
        ),
        migrations.CreateModel(
            name='EmailTwoFactorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_hash', models.CharField(max_length=128)),
                ('purpose', models.CharField(default='login', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('challenge_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_2fa_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_two_factor_codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['challenge_token', 'is_used'], name='email_two_f_challen_0efc74_idx'), models.Index(fields=['user', 'is_used', 'expires_at'], name='email_two_f_user_id_49030f_idx')],
            },
        ),
    ]
