# Generated by Django 6.0.3 on 2026-03-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_twofactorauth_method_emailtwofactorcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtwofactorcode',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
    ]
