# Generated by Django 6.0.3 on 2026-03-30 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_roles_permissions'),
        ('api', '0007_add_default_to_user_agent'),
    ]

    operations = [
    ]
