# Generated by Django 6.0.3 on 2026-03-30 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20260330_0419'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_type', models.CharField(choices=[('saas_admin', 'Superadministrador SaaS'), ('tenant_user', 'Usuario de Tenant')], default='tenant_user', help_text='Tipo de usuario en el sistema', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('position', models.CharField(blank=True, help_text='Cargo o posición', max_length=100)),
                ('department', models.CharField(blank=True, help_text='Departamento', max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('timezone', models.CharField(default='America/La_Paz', max_length=50)),
                ('language', models.CharField(default='es', max_length=10)),
                ('notification_preferences', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Usuario que asignó este rol', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_assignments', to='api.financialinstitution')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='api.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_roles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'institution', 'is_active'], name='user_roles_user_id_53d727_idx'), models.Index(fields=['role', 'is_active'], name='user_roles_role_id_57352b_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'role', 'institution'), name='uniq_user_role_institution')],
            },
        ),
    ]
