# Generated by Django 6.0.3 on 2026-03-30 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_role_from_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authchallenge',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='institution',
            field=models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='api.financialinstitution'),
        ),
    ]
