# Generated by Django 6.0.4 on 2026-05-27 19:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0017_merge_20260516_0303'),
        ('storage', '0001_create_file_resource_model'),
        ('tenants', '0003_create_file_resource_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collateral_type', models.CharField(choices=[('REAL_ESTATE', 'Real Estate'), ('VEHICLE', 'Vehicle'), ('MACHINERY', 'Machinery'), ('SAVINGS', 'Savings'), ('GUARANTOR', 'Guarantor'), ('OTHER', 'Other')], db_index=True, max_length=20, verbose_name='Collateral Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estimated Value')),
                ('appraised_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Appraised Value')),
                ('coverage_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Coverage over the approved loan amount', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Coverage Percentage')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RELEASED', 'Released')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('property_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Property Address')),
                ('property_registry_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Property Registry Number')),
                ('property_area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Property Area (m2)')),
                ('vehicle_plate', models.CharField(blank=True, max_length=20, null=True, verbose_name='Vehicle Plate')),
                ('vehicle_vin', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vehicle VIN')),
                ('vehicle_year', models.IntegerField(blank=True, null=True, verbose_name='Vehicle Year')),
                ('vehicle_brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vehicle Brand')),
                ('vehicle_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vehicle Model')),
                ('ownership_verified', models.BooleanField(default=False, verbose_name='Ownership Verified')),
                ('has_liens', models.BooleanField(default=False, verbose_name='Has Liens')),
                ('lien_details', models.TextField(blank=True, verbose_name='Lien Details')),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Insurance Policy Number')),
                ('insurance_company', models.CharField(blank=True, max_length=150, null=True, verbose_name='Insurance Company')),
                ('insurance_expiry_date', models.DateField(blank=True, null=True, verbose_name='Insurance Expiry Date')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_collaterals', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaterals', to='loans.loanapplication', verbose_name='Loan Application')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_collaterals', to=settings.AUTH_USER_MODEL, verbose_name='Registered By')),
            ],
            options={
                'verbose_name': 'Collateral',
                'verbose_name_plural': 'Collaterals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollateralDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('DEED', 'Deed'), ('APPRAISAL', 'Appraisal'), ('PHOTOS', 'Photos'), ('INSURANCE', 'Insurance'), ('REGISTRATION', 'Registration'), ('OTHER', 'Other')], db_index=True, max_length=20, verbose_name='Document Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('is_valid', models.BooleanField(default=False, verbose_name='Valid')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('collateral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='garantias.collateral', verbose_name='Collateral')),
                ('file_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collateral_documents', to='storage.fileresource', verbose_name='File Resource')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_collateral_documents', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_collateral_documents', to=settings.AUTH_USER_MODEL, verbose_name='Verified By')),
            ],
            options={
                'verbose_name': 'Collateral Document',
                'verbose_name_plural': 'Collateral Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollateralValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valuation_type', models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External'), ('MARKET_COMPARISON', 'Market Comparison')], max_length=30, verbose_name='Valuation Type')),
                ('appraiser_name', models.CharField(max_length=200, verbose_name='Appraiser Name')),
                ('appraiser_license', models.CharField(blank=True, max_length=100, null=True, verbose_name='Appraiser License')),
                ('appraiser_company', models.CharField(blank=True, max_length=200, null=True, verbose_name='Appraiser Company')),
                ('valuation_date', models.DateField(verbose_name='Valuation Date')),
                ('appraised_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Appraised Value')),
                ('valuation_method', models.TextField(blank=True, verbose_name='Valuation Method')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Valid Until')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_collateral_valuations', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('collateral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='garantias.collateral', verbose_name='Collateral')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
                ('report_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collateral_valuations', to='storage.fileresource', verbose_name='Report File')),
            ],
            options={
                'verbose_name': 'Collateral Valuation',
                'verbose_name_plural': 'Collateral Valuations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('document_type', models.CharField(choices=[('CI', 'Identity Card'), ('NIT', 'Tax ID'), ('PASSPORT', 'Passport')], max_length=20, verbose_name='Document Type')),
                ('document_number', models.CharField(max_length=30, verbose_name='Document Number')),
                ('document_extension', models.CharField(blank=True, max_length=10, null=True, verbose_name='Document Extension')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True, verbose_name='Gender')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('mobile_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile Phone')),
                ('address', models.TextField(verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
                ('employment_type', models.CharField(choices=[('EMPLOYED', 'Employed'), ('SELF_EMPLOYED', 'Self Employed'), ('BUSINESS_OWNER', 'Business Owner'), ('RETIRED', 'Retired'), ('OTHER', 'Other')], max_length=20, verbose_name='Employment Type')),
                ('employer_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Employer Name')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Job Title')),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monthly Income')),
                ('relationship_to_borrower', models.CharField(max_length=100, verbose_name='Relationship To Borrower')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_guarantors', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('collateral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantors', to='garantias.collateral', verbose_name='Related Collateral')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='loans.loanapplication', verbose_name='Loan Application')),
            ],
            options={
                'verbose_name': 'Guarantor',
                'verbose_name_plural': 'Guarantors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='collateral',
            index=models.Index(fields=['institution', 'loan_application'], name='garantias_c_institu_b3383d_idx'),
        ),
        migrations.AddIndex(
            model_name='collateral',
            index=models.Index(fields=['institution', 'status'], name='garantias_c_institu_274221_idx'),
        ),
        migrations.AddIndex(
            model_name='collateral',
            index=models.Index(fields=['collateral_type'], name='garantias_c_collate_2c225f_idx'),
        ),
        migrations.AddIndex(
            model_name='collateral',
            index=models.Index(fields=['is_active'], name='garantias_c_is_acti_73bcb3_idx'),
        ),
        migrations.AddIndex(
            model_name='collateraldocument',
            index=models.Index(fields=['collateral', 'document_type'], name='garantias_c_collate_85f34e_idx'),
        ),
        migrations.AddIndex(
            model_name='collateraldocument',
            index=models.Index(fields=['is_valid'], name='garantias_c_is_vali_16d561_idx'),
        ),
        migrations.AddIndex(
            model_name='collateralvaluation',
            index=models.Index(fields=['collateral', 'valuation_date'], name='garantias_c_collate_a841da_idx'),
        ),
        migrations.AddIndex(
            model_name='collateralvaluation',
            index=models.Index(fields=['approved_at'], name='garantias_c_approve_f9cf5e_idx'),
        ),
        migrations.AddIndex(
            model_name='guarantor',
            index=models.Index(fields=['institution', 'loan_application'], name='garantias_g_institu_3fd76e_idx'),
        ),
        migrations.AddIndex(
            model_name='guarantor',
            index=models.Index(fields=['institution', 'document_number'], name='garantias_g_institu_f37aad_idx'),
        ),
        migrations.AddIndex(
            model_name='guarantor',
            index=models.Index(fields=['status'], name='garantias_g_status_e235f8_idx'),
        ),
        migrations.AddIndex(
            model_name='guarantor',
            index=models.Index(fields=['is_active'], name='garantias_g_is_acti_6116f9_idx'),
        ),
    ]
