# Generated by Django 6.0.3 on 2026-04-21 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_type', models.CharField(choices=[('saas_admin', 'Superadministrador SaaS'), ('tenant_user', 'Usuario de Tenant'), ('client', 'Cliente/Prestatario')], default='tenant_user', help_text='Tipo de usuario en el sistema', max_length=20, verbose_name='Tipo de Usuario')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('position', models.CharField(blank=True, help_text='Cargo o posición', max_length=100, verbose_name='Cargo')),
                ('department', models.CharField(blank=True, help_text='Departamento', max_length=100, verbose_name='Departamento')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('timezone', models.CharField(default='America/La_Paz', max_length=50, verbose_name='Zona Horaria')),
                ('language', models.CharField(default='es', max_length=10, verbose_name='Idioma')),
                ('notification_preferences', models.JSONField(blank=True, default=dict, verbose_name='Preferencias de Notificación')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'db_table': 'user_profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
