# Generated by Django 6.0.2 on 2026-05-05 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_add_cu11_fields_and_status_history'),
        ('identity_verification', '0001_initial'),
        ('tenants', '0002_tenantbranding'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='identityverification',
            new_name='identity_ve_institu_003d51_idx',
            old_name='identity_ve_instit_user_idx',
        ),
        migrations.RenameIndex(
            model_name='identityverification',
            new_name='identity_ve_institu_481a64_idx',
            old_name='identity_ve_instit_status_idx',
        ),
        migrations.RenameIndex(
            model_name='identityverification',
            new_name='identity_ve_user_id_68a21f_idx',
            old_name='identity_ve_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='identityverification',
            new_name='identity_ve_provide_02f928_idx',
            old_name='identity_ve_session_provider_idx',
        ),
        migrations.RenameIndex(
            model_name='identityverification',
            new_name='identity_ve_credit__64138f_idx',
            old_name='identity_ve_app_status_idx',
        ),
        migrations.RenameIndex(
            model_name='identityverificationwebhook',
            new_name='identity_ve_provide_7e17d2_idx',
            old_name='identity_ve_provider_event_idx',
        ),
        migrations.RenameIndex(
            model_name='identityverificationwebhook',
            new_name='identity_ve_provide_79dffd_idx',
            old_name='identity_ve_session_status_idx',
        ),
        migrations.RenameIndex(
            model_name='identityverificationwebhook',
            new_name='identity_ve_receive_b42019_idx',
            old_name='identity_ve_received_idx',
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Sucursal donde se originó la solicitud', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_verifications', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='institution',
            field=models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution'),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='provider_session_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID único de sesión en el proveedor (e.g., Didit session_id)', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='provider_session_token',
            field=models.CharField(blank=True, help_text='Token de sesión del proveedor (si aplica y es necesario). SENSIBLE.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='identityverification',
            name='verification_url',
            field=models.URLField(blank=True, help_text='URL del hosting Didit o similar donde el usuario completa la verificación', null=True),
        ),
    ]
