# Generated by Django 6.0 on 2026-04-11 09:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('code', models.CharField(help_text='Código único identificador del producto', max_length=50, unique=True, verbose_name='Código del Producto')),
                ('product_type', models.CharField(choices=[('PERSONAL', 'Crédito Personal/Consumo'), ('VEHICULAR', 'Crédito Vehicular'), ('HIPOTECARIO', 'Crédito Hipotecario'), ('VIVIENDA_SOCIAL', 'Crédito Vivienda Social'), ('PYME', 'Crédito PYME'), ('EMPRESARIAL', 'Crédito Empresarial'), ('AGROPECUARIO', 'Crédito Agropecuario'), ('MICROEMPRESA', 'Microcrédito')], max_length=20, verbose_name='Tipo de Producto')),
                ('description', models.TextField(help_text='Descripción detallada del producto crediticio', verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el producto está disponible para solicitudes', verbose_name='Activo')),
                ('display_order', models.IntegerField(default=0, help_text='Orden en que se muestra el producto (menor primero)', verbose_name='Orden de Visualización')),
                ('min_amount', models.DecimalField(decimal_places=2, help_text='Monto mínimo del crédito en Bolivianos', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Mínimo (Bs)')),
                ('max_amount', models.DecimalField(decimal_places=2, help_text='Monto máximo del crédito en Bolivianos', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Máximo (Bs)')),
                ('min_term_months', models.IntegerField(help_text='Plazo mínimo del crédito en meses', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Plazo Mínimo (meses)')),
                ('max_term_months', models.IntegerField(help_text='Plazo máximo del crédito en meses', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Plazo Máximo (meses)')),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Tasa de interés anual nominal', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tasa de Interés Anual (%)')),
                ('interest_type', models.CharField(choices=[('FIXED', 'Tasa Fija'), ('VARIABLE', 'Tasa Variable'), ('MIXED', 'Tasa Mixta')], default='FIXED', max_length=10, verbose_name='Tipo de Tasa')),
                ('effective_annual_rate', models.DecimalField(blank=True, decimal_places=2, help_text='TEA - Incluye comisiones y seguros', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tasa Efectiva Anual (%)')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, help_text='Comisión sobre el monto del crédito', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Comisión (%)')),
                ('insurance_rate', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje mensual sobre saldo deudor', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Seguro de Desgravamen (%)')),
                ('additional_insurance_rate', models.DecimalField(decimal_places=2, default=0, help_text='Seguro del bien (vehicular/hipotecario)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Seguro Adicional (%)')),
                ('payment_frequency', models.CharField(choices=[('MONTHLY', 'Mensual'), ('BIWEEKLY', 'Quincenal'), ('WEEKLY', 'Semanal')], default='MONTHLY', max_length=10, verbose_name='Frecuencia de Pago')),
                ('amortization_system', models.CharField(choices=[('FRENCH', 'Sistema Francés (Cuota Fija)'), ('GERMAN', 'Sistema Alemán (Cuota Decreciente)'), ('AMERICAN', 'Sistema Americano (Solo Intereses)')], default='FRENCH', max_length=10, verbose_name='Sistema de Amortización')),
                ('grace_period_months', models.IntegerField(default=0, help_text='Meses sin pago de capital al inicio', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Período de Gracia (meses)')),
                ('allows_early_payment', models.BooleanField(default=True, verbose_name='Permite Pago Anticipado')),
                ('early_payment_penalty', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje sobre el saldo anticipado', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Penalidad Pago Anticipado (%)')),
                ('min_income_required', models.DecimalField(blank=True, decimal_places=2, help_text='Ingreso líquido mensual mínimo', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ingreso Mínimo Requerido (Bs)')),
                ('max_debt_to_income_ratio', models.DecimalField(decimal_places=2, default=40.0, help_text='RCI máximo permitido (típicamente 40%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Relación Cuota-Ingreso Máxima (%)')),
                ('min_employment_months', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Antigüedad Laboral Mínima (meses)')),
                ('requires_guarantor', models.BooleanField(default=False, verbose_name='Requiere Garante')),
                ('requires_collateral', models.BooleanField(default=False, help_text='Hipoteca, prenda, etc.', verbose_name='Requiere Garantía Real')),
                ('min_collateral_coverage', models.DecimalField(decimal_places=2, default=100.0, help_text='Valor garantía / Monto crédito (típicamente 125%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cobertura Mínima de Garantía (%)')),
                ('required_documents', models.JSONField(blank=True, default=list, help_text='Lista de documentos necesarios para solicitar', verbose_name='Documentos Requeridos')),
                ('min_credit_score', models.IntegerField(blank=True, help_text='Score mínimo para aprobación automática', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Score Crediticio Mínimo')),
                ('auto_approval_enabled', models.BooleanField(default=False, help_text='Permite aprobación sin revisión manual si cumple criterios', verbose_name='Aprobación Automática Habilitada')),
                ('max_auto_approval_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Montos superiores requieren revisión manual', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Máximo Aprobación Automática (Bs)')),
                ('target_audience', models.TextField(blank=True, help_text='Descripción del perfil de cliente ideal', null=True, verbose_name='Público Objetivo')),
                ('benefits', models.JSONField(blank=True, default=list, help_text='Lista de beneficios del producto', verbose_name='Beneficios')),
                ('terms_and_conditions', models.TextField(blank=True, null=True, verbose_name='Términos y Condiciones')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
            ],
            options={
                'verbose_name': 'Producto Crediticio',
                'verbose_name_plural': 'Productos Crediticios',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement_name', models.CharField(max_length=200, verbose_name='Nombre del Requisito')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Obligatorio')),
                ('display_order', models.IntegerField(default=0, verbose_name='Orden')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_requirements', to='products.creditproduct', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Requisito de Producto',
                'verbose_name_plural': 'Requisitos de Productos',
                'ordering': ['display_order', 'requirement_name'],
            },
        ),
        migrations.AddIndex(
            model_name='creditproduct',
            index=models.Index(fields=['product_type'], name='products_cr_product_5aa762_idx'),
        ),
        migrations.AddIndex(
            model_name='creditproduct',
            index=models.Index(fields=['is_active'], name='products_cr_is_acti_786388_idx'),
        ),
        migrations.AddIndex(
            model_name='creditproduct',
            index=models.Index(fields=['institution', 'is_active'], name='products_cr_institu_5928b9_idx'),
        ),
    ]
