# Generated by Django 6.0.4 on 2026-05-10 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0013_add_product_document_requirement_field'),
        ('products', '0003_add_ruleset_and_documents'),
        ('tenants', '0003_create_file_resource_model'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='creditproduct',
            name='products_cr_is_acti_786388_idx',
        ),
        migrations.RemoveIndex(
            model_name='creditproduct',
            name='products_cr_rule_se_idx',
        ),
        migrations.RenameIndex(
            model_name='creditproduct',
            new_name='products_cr_product_bc75e5_idx',
            old_name='products_cr_product_5aa762_idx',
        ),
        migrations.RenameIndex(
            model_name='creditproduct',
            new_name='products_cr_product_bc75e5_idx',
            old_name='products_cr_product_idx',
        ),
        migrations.AddField(
            model_name='creditproduct',
            name='color',
            field=models.CharField(blank=True, help_text='Color para UI (ej: blue, green, purple)', max_length=20, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='creditproduct',
            name='icon',
            field=models.CharField(blank=True, help_text='Nombre del ícono de lucide-react', max_length=50, verbose_name='Ícono'),
        ),
        migrations.AlterField(
            model_name='creditproduct',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el producto está disponible para solicitudes', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='creditproduct',
            name='product_type',
            field=models.ForeignKey(help_text='Tipo de producto desde catálogo centralizado', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='loans.producttype', verbose_name='Tipo de Producto'),
        ),
        migrations.AlterField(
            model_name='creditproduct',
            name='target_audience',
            field=models.TextField(blank=True, help_text='Descripción del perfil de cliente ideal', verbose_name='Público Objetivo'),
        ),
        migrations.AlterField(
            model_name='creditproduct',
            name='terms_and_conditions',
            field=models.TextField(blank=True, verbose_name='Términos y Condiciones'),
        ),
        migrations.AlterField(
            model_name='productdocumentrequirement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productdocumentrequirement',
            name='institution',
            field=models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution'),
        ),
        migrations.AlterField(
            model_name='productdocumentrequirement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
