# Generated by Django 6.0.4 on 2026-05-10 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0015_add_product_selections'),
        ('products', '0004_add_product_document_requirement_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditproduct',
            name='selected_eligibility_rules',
            field=models.ManyToManyField(blank=True, help_text='Reglas de elegibilidad específicas a aplicar', related_name='products_using', to='loans.eligibilityrule', verbose_name='Reglas de Elegibilidad'),
        ),
        migrations.AddField(
            model_name='creditproduct',
            name='selected_parameter',
            field=models.ForeignKey(blank=True, help_text='Parámetro específico del conjunto de reglas a usar', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_using', to='loans.creditproductparameter', verbose_name='Parámetro Seleccionado'),
        ),
        migrations.AddField(
            model_name='creditproduct',
            name='selected_threshold',
            field=models.ForeignKey(blank=True, help_text='Umbral de scoring/decisión a usar', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_using', to='loans.decisionthreshold', verbose_name='Umbral de Decisión'),
        ),
    ]
