# Generated by Django 6.0.4 on 2026-04-12 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('institution_type', models.CharField(choices=[('banking', 'Banco Comercial'), ('microfinance', 'Microfinanciera'), ('cooperative', 'Cooperativa de Credito'), ('fintech', 'Fintech')], default='banking', max_length=20, verbose_name='Tipo de Institución')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_financial_institutions', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Institución Financiera',
                'verbose_name_plural': 'Instituciones Financieras',
                'db_table': 'financial_institutions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialInstitutionMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.financialinstitution', verbose_name='Institución')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Membresía de Institución',
                'verbose_name_plural': 'Membresías de Instituciones',
                'db_table': 'financial_institution_memberships',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('institution', 'user'), name='uniq_institution_user_membership')],
            },
        ),
    ]
