# Generated by Django 6.0.3 on 2026-05-02 02:27

import api.tenants.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(help_text='Nombre institucional que se mostrará en la interfaz', max_length=255, verbose_name='Nombre Visible')),
                ('logo', models.FileField(blank=True, help_text='Logo principal para la interfaz white-label', null=True, upload_to=api.tenants.models.tenant_branding_logo_upload_to, verbose_name='Logo Principal')),
                ('primary_color', models.CharField(default='#2563EB', max_length=7, verbose_name='Color Primario')),
                ('secondary_color', models.CharField(default='#0F172A', max_length=7, verbose_name='Color Secundario')),
                ('accent_color', models.CharField(default='#0EA5E9', max_length=7, verbose_name='Color de Acento')),
                ('background_color', models.CharField(default='#F8FAFC', max_length=7, verbose_name='Color de Fondo')),
                ('text_color', models.CharField(default='#0F172A', max_length=7, verbose_name='Color de Texto')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la personalización está aplicada', verbose_name='Activo')),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='tenants.financialinstitution', verbose_name='Institución Financiera')),
            ],
            options={
                'verbose_name': 'Personalización Visual del Tenant',
                'verbose_name_plural': 'Personalizaciones Visuales de Tenant',
                'db_table': 'tenant_branding',
                'ordering': ['institution__name'],
                'indexes': [models.Index(fields=['institution'], name='tenant_bran_institu_cae7d9_idx'), models.Index(fields=['is_active'], name='tenant_bran_is_acti_a0ff4b_idx')],
            },
        ),
    ]
