# Generated by Django 6.0.4 on 2026-05-06 09:04

import api.tenants.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_create_file_resource_model'),
        ('tenants', '0002_tenantbranding'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantbranding',
            name='cover_file',
            field=models.ForeignKey(blank=True, help_text='Imagen de portada para landing page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_tenant', to='storage.fileresource', verbose_name='Archivo de Imagen de Portada'),
        ),
        migrations.AddField(
            model_name='tenantbranding',
            name='favicon_file',
            field=models.ForeignKey(blank=True, help_text='Favicon para el navegador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favicon_for_tenant', to='storage.fileresource', verbose_name='Archivo de Favicon'),
        ),
        migrations.AddField(
            model_name='tenantbranding',
            name='logo_file',
            field=models.ForeignKey(blank=True, help_text='Logo principal de la institución', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo_for_tenant', to='storage.fileresource', verbose_name='Archivo de Logo'),
        ),
        migrations.AlterField(
            model_name='tenantbranding',
            name='logo',
            field=models.FileField(blank=True, help_text='DEPRECADO: Usar logo_file en su lugar', null=True, upload_to=api.tenants.models.tenant_branding_logo_upload_to, verbose_name='Logo Principal (DEPRECADO)'),
        ),
    ]
