# Generated by Django 6.0.4 on 2026-05-30 23:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garantias', '0001_initial'),
        ('loans', '0018_loanapplication_contract_generated'),
        ('products', '0005_add_product_selections'),
        ('storage', '0001_create_file_resource_model'),
        ('tenants', '0003_create_file_resource_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_number', models.CharField(help_text='Número único de identificación del contrato', max_length=50, unique=True, verbose_name='Número de Contrato')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PENDING_SIGNATURE', 'Pendiente de Firma'), ('PARTIALLY_SIGNED', 'Parcialmente Firmado'), ('ACTIVE', 'Activo'), ('CANCELLED', 'Cancelado'), ('COMPLETED', 'Completado'), ('DEFAULTED', 'En Mora')], db_index=True, default='DRAFT', max_length=20, verbose_name='Estado')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Principal')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Tasa de Interés Anual (%)')),
                ('term_months', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(360)], verbose_name='Plazo en Meses')),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cuota Mensual')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Capital + Intereses', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Total a Pagar')),
                ('contract_date', models.DateField(help_text='Fecha de generación del contrato', verbose_name='Fecha del Contrato')),
                ('start_date', models.DateField(help_text='Fecha de inicio del crédito', verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(help_text='Fecha estimada de finalización del crédito', verbose_name='Fecha de Finalización')),
                ('first_payment_date', models.DateField(help_text='Fecha de vencimiento del primer pago', verbose_name='Fecha del Primer Pago')),
                ('borrower_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Firma del Prestatario')),
                ('borrower_signature_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Firma del Prestatario')),
                ('borrower_signature_data', models.TextField(blank=True, help_text='Hash o datos criptográficos de la firma', verbose_name='Datos de Firma del Prestatario')),
                ('terms_and_conditions', models.TextField(help_text='Términos y condiciones específicos de este contrato', verbose_name='Términos y Condiciones')),
                ('special_clauses', models.JSONField(blank=True, default=dict, help_text='Cláusulas adicionales específicas de este contrato', verbose_name='Cláusulas Especiales')),
                ('version', models.PositiveIntegerField(default=1, help_text='Versión del contrato (se incrementa si se regenera)', verbose_name='Versión')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Publicación')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cancelación')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Motivo de Cancelación')),
                ('notes', models.TextField(blank=True, verbose_name='Notas Internas')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Cancelado Por')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Generado Por')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
                ('loan_application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='loans.loanapplication', verbose_name='Solicitud de Crédito')),
                ('pdf_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_as_pdf', to='storage.fileresource', verbose_name='Archivo PDF del Contrato')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Publicado Por')),
            ],
            options={
                'verbose_name': 'Contrato de Crédito',
                'verbose_name_plural': 'Contratos de Crédito',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('ADDENDUM', 'Addendum'), ('ANNEX', 'Anexo'), ('GUARANTEE', 'Documento de Garantía'), ('INSURANCE', 'Póliza de Seguro'), ('AMENDMENT', 'Enmienda'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tipo de Documento')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_required', models.BooleanField(default=False, help_text='Si es un documento obligatorio', verbose_name='Requerido')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_documents', to='contracts.contract', verbose_name='Contrato')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_documents', to='storage.fileresource', verbose_name='Archivo')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_contract_documents', to=settings.AUTH_USER_MODEL, verbose_name='Subido Por')),
            ],
            options={
                'verbose_name': 'Documento de Contrato',
                'verbose_name_plural': 'Documentos de Contrato',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Plantilla')),
                ('code', models.CharField(help_text='Código único identificador de la plantilla', max_length=50, verbose_name='Código')),
                ('template_content', models.TextField(help_text='HTML con variables como {{borrower_name}}, {{amount}}, etc.', verbose_name='Contenido de la Plantilla')),
                ('available_variables', models.JSONField(blank=True, default=list, help_text='Lista de variables que se pueden usar en la plantilla', verbose_name='Variables Disponibles')),
                ('is_active', models.BooleanField(default=True, help_text='Solo las plantillas activas pueden usarse para generar contratos', verbose_name='Activa')),
                ('is_default', models.BooleanField(default=False, help_text='Se usa cuando no hay plantilla específica para el producto', verbose_name='Plantilla por Defecto')),
                ('requires_guarantor_signature', models.BooleanField(default=False, help_text='Si es True, los garantes deben firmar el contrato', verbose_name='Requiere Firma de Garante')),
                ('terms_and_conditions', models.TextField(blank=True, help_text='Términos legales que se incluyen en el contrato', verbose_name='Términos y Condiciones')),
                ('legal_clauses', models.JSONField(blank=True, default=list, help_text='Lista de cláusulas legales adicionales', verbose_name='Cláusulas Legales')),
                ('description', models.TextField(blank=True, help_text='Descripción de la plantilla y su uso', verbose_name='Descripción')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Versión')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
                ('product', models.ForeignKey(blank=True, help_text='Si se especifica, esta plantilla se usa solo para este producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_templates', to='products.creditproduct', verbose_name='Producto Crediticio')),
            ],
            options={
                'verbose_name': 'Plantilla de Contrato',
                'verbose_name_plural': 'Plantillas de Contrato',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='contracts.contracttemplate', verbose_name='Plantilla Utilizada'),
        ),
        migrations.CreateModel(
            name='ContractAmortizationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_number', models.PositiveIntegerField(help_text='Número secuencial de la cuota (1, 2, 3, ...)', verbose_name='Número de Cuota')),
                ('due_date', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Monto de Capital')),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Monto de Interés')),
                ('total_payment', models.DecimalField(decimal_places=2, help_text='Capital + Interés', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Cuota Total')),
                ('remaining_balance', models.DecimalField(decimal_places=2, help_text='Saldo de capital después de esta cuota', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Saldo Pendiente')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pagado')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Monto Pagado')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia de Pago')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortization_schedule', to='contracts.contract', verbose_name='Contrato')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
            ],
            options={
                'verbose_name': 'Cuota de Amortización',
                'verbose_name_plural': 'Tabla de Amortización',
                'ordering': ['contract', 'payment_number'],
                'indexes': [models.Index(fields=['contract', 'payment_number'], name='contracts_c_contrac_61f6ab_idx'), models.Index(fields=['contract', 'due_date'], name='contracts_c_contrac_918a78_idx'), models.Index(fields=['contract', 'is_paid'], name='contracts_c_contrac_30d564_idx')],
                'unique_together': {('contract', 'payment_number')},
            },
        ),
        migrations.CreateModel(
            name='ContractSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signer_type', models.CharField(choices=[('BORROWER', 'Prestatario'), ('GUARANTOR', 'Garante'), ('INSTITUTION', 'Institución')], max_length=20, verbose_name='Tipo de Firmante')),
                ('signed_at', models.DateTimeField(verbose_name='Fecha y Hora de Firma')),
                ('signature_method', models.CharField(choices=[('DIGITAL', 'Firma Digital Simple'), ('BIOMETRIC', 'Firma Biométrica'), ('OTP', 'Verificación OTP'), ('DOCUSIGN', 'DocuSign'), ('ADOBE_SIGN', 'Adobe Sign')], default='DIGITAL', max_length=50, verbose_name='Método de Firma')),
                ('signature_data', models.TextField(help_text='Hash criptográfico o datos de verificación de la firma', verbose_name='Datos de la Firma')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('device_info', models.JSONField(blank=True, default=dict, help_text='User-agent, sistema operativo, navegador, etc.', verbose_name='Información del Dispositivo')),
                ('geolocation', models.JSONField(blank=True, default=dict, help_text='Datos de ubicación si están disponibles', verbose_name='Geolocalización')),
                ('identity_verified', models.BooleanField(default=False, help_text='Si se verificó la identidad antes de firmar', verbose_name='Identidad Verificada')),
                ('verification_method', models.CharField(blank=True, help_text='Método usado para verificar identidad (2FA, biométrico, etc.)', max_length=50, verbose_name='Método de Verificación')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='contracts.contract', verbose_name='Contrato')),
                ('guarantor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_signatures', to='garantias.guarantor', verbose_name='Garante Firmante')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_signatures', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Firmante')),
            ],
            options={
                'verbose_name': 'Firma de Contrato',
                'verbose_name_plural': 'Firmas de Contrato',
                'ordering': ['signed_at'],
                'indexes': [models.Index(fields=['contract', 'signer_type'], name='contracts_c_contrac_0967c4_idx'), models.Index(fields=['signed_at'], name='contracts_c_signed__e562eb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='contracttemplate',
            index=models.Index(fields=['institution', 'is_active'], name='contracts_c_institu_4dc598_idx'),
        ),
        migrations.AddIndex(
            model_name='contracttemplate',
            index=models.Index(fields=['institution', 'product'], name='contracts_c_institu_6abc2c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contracttemplate',
            unique_together={('institution', 'code')},
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['institution', 'status'], name='contracts_c_institu_bc34c0_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['institution', 'loan_application'], name='contracts_c_institu_1d91cf_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contract_number'], name='contracts_c_contrac_876f48_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contract_date'], name='contracts_c_contrac_ac5933_idx'),
        ),
    ]
