# Generated by Django 6.0 on 2026-04-11 09:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_type', models.CharField(choices=[('NATURAL', 'Persona Natural'), ('JURIDICA', 'Persona Jurídica')], default='NATURAL', max_length=10, verbose_name='Tipo de Cliente')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('document_type', models.CharField(choices=[('CI', 'Cédula de Identidad'), ('NIT', 'Número de Identificación Tributaria'), ('PASSPORT', 'Pasaporte'), ('RUC', 'Registro Único de Contribuyentes')], default='CI', max_length=10, verbose_name='Tipo de Documento')),
                ('document_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El número de documento solo puede contener letras mayúsculas, números y guiones', regex='^[A-Z0-9\\-]+$')], verbose_name='Número de Documento')),
                ('document_extension', models.CharField(blank=True, help_text='Ej: LP, SC, CB, OR, PT, TJ, CH, BE, PD', max_length=5, null=True, verbose_name='Extensión CI')),
                ('birth_date', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True, verbose_name='Género')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido', regex='^\\+?[0-9\\s\\-\\(\\)]+$')], verbose_name='Teléfono')),
                ('mobile_phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido', regex='^\\+?[0-9\\s\\-\\(\\)]+$')], verbose_name='Teléfono Móvil')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('department', models.CharField(help_text='Ej: La Paz, Santa Cruz, Cochabamba', max_length=100, verbose_name='Departamento')),
                ('country', models.CharField(default='Bolivia', max_length=100, verbose_name='País')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal')),
                ('employment_status', models.CharField(choices=[('EMPLOYED', 'Empleado en relación de dependencia'), ('SELF_EMPLOYED', 'Trabajador independiente'), ('BUSINESS_OWNER', 'Propietario de negocio'), ('RETIRED', 'Jubilado'), ('UNEMPLOYED', 'Desempleado'), ('OTHER', 'Otro')], max_length=20, verbose_name='Estado Laboral')),
                ('employer_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Empleador/Empresa')),
                ('employer_nit', models.CharField(blank=True, max_length=20, null=True, verbose_name='NIT del Empleador')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('employment_start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio Laboral')),
                ('monthly_income', models.DecimalField(decimal_places=2, help_text='Ingreso líquido mensual en Bolivianos', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ingreso Mensual Neto (Bs)')),
                ('additional_income', models.DecimalField(decimal_places=2, default=0, help_text='Otros ingresos mensuales', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ingresos Adicionales (Bs)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('verified_at', models.DateTimeField(blank=True, help_text='Fecha en que se verificó la identidad del cliente', null=True, verbose_name='Fecha de Verificación')),
                ('kyc_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('VERIFIED', 'Verificado'), ('REJECTED', 'Rechazado'), ('EXPIRED', 'Expirado')], default='PENDING', max_length=20, verbose_name='Estado KYC')),
                ('risk_level', models.CharField(blank=True, choices=[('LOW', 'Bajo'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto')], max_length=10, null=True, verbose_name='Nivel de Riesgo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas Internas')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_clients', to=settings.AUTH_USER_MODEL, verbose_name='Verificado Por')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('IDENTITY', 'Documento de Identidad'), ('INCOME', 'Comprobante de Ingresos'), ('ADDRESS', 'Comprobante de Domicilio'), ('EMPLOYMENT', 'Documento Laboral'), ('BANK', 'Extracto Bancario'), ('TAX', 'Documento Tributario'), ('OTHER', 'Otro')], max_length=20, verbose_name='Categoría')),
                ('document_name', models.CharField(max_length=200, verbose_name='Nombre del Documento')),
                ('file', models.FileField(upload_to='clients/documents/%Y/%m/', verbose_name='Archivo')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='Tamaño del Archivo (bytes)')),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo MIME')),
                ('verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Verificación')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.client', verbose_name='Cliente')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_client_documents', to=settings.AUTH_USER_MODEL, verbose_name='Subido Por')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_client_documents', to=settings.AUTH_USER_MODEL, verbose_name='Verificado Por')),
            ],
            options={
                'verbose_name': 'Documento de Cliente',
                'verbose_name_plural': 'Documentos de Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['document_number'], name='clients_cli_documen_3e4aa4_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email'], name='clients_cli_email_56b9fc_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['institution', 'document_number'], name='clients_cli_institu_24cff0_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['kyc_status'], name='clients_cli_kyc_sta_0cc6ec_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_active'], name='clients_cli_is_acti_57c1e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('institution', 'document_number'), name='unique_client_per_institution'),
        ),
    ]
