# Generated by Django 6.0.3 on 2026-05-03 21:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_duplicate_fields'),
        ('tenants', '0002_tenantbranding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='clients_cli_email_56b9fc_idx',
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['user'], name='clients_cli_user_id_f4ed69_idx'),
        ),
    ]
