# Generated by Django 6.0.2 on 2026-04-21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Nombre de la sucursal', max_length=150, verbose_name='Nombre')),
                ('address', models.CharField(help_text='Dirección física de la sucursal', max_length=255, verbose_name='Dirección')),
                ('city', models.CharField(help_text='Ciudad donde se ubica la sucursal', max_length=120, verbose_name='Ciudad')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la sucursal está activa', verbose_name='Activa')),
                ('assigned_loan_applications', models.ManyToManyField(blank=True, help_text='Solicitudes de crédito asociadas a esta sucursal', related_name='assigned_branches', to='loans.loanapplication', verbose_name='Solicitudes Asignadas')),
                ('assigned_users', models.ManyToManyField(blank=True, help_text='Usuarios internos asignados a esta sucursal', related_name='assigned_branches', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios Asignados')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='branch_set', to='tenants.financialinstitution')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'branches',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('institution', 'name'), name='uniq_branch_name_per_institution'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['institution', 'is_active'], name='branches_institution_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['institution', 'city'], name='branches_institution_city_idx'),
        ),
    ]
