# Generated by Django 6.0.3 on 2026-05-03 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('tenants', '0002_tenantbranding'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='branch',
            new_name='branches_institu_099bf2_idx',
            old_name='branches_institution_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='branch',
            new_name='branches_institu_b23520_idx',
            old_name='branches_institution_city_idx',
        ),
        migrations.AlterField(
            model_name='branch',
            name='institution',
            field=models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution'),
        ),
    ]
