# Generated by Django 6.0.4 on 2026-04-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_timesta_e93820_idx',
            old_name='audit_logs_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_user_id_e11c73_idx',
            old_name='audit_logs_user_id_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_institu_98e9b4_idx',
            old_name='audit_logs_institu_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_action_f48619_idx',
            old_name='audit_logs_action_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_severit_83c56b_idx',
            old_name='audit_logs_severit_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='security_ev_timesta_c6e1c5_idx',
            old_name='security_e_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='security_ev_ip_addr_1bdf28_idx',
            old_name='security_e_ip_addr_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='security_ev_event_t_7f1ed6_idx',
            old_name='security_e_event_t_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='security_ev_resolve_bb7e0d_idx',
            old_name='security_e_resolve_timesta_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login_success', 'Login Exitoso'), ('login_failed', 'Login Fallido'), ('logout', 'Logout'), ('register', 'Registro'), ('password_reset_request', 'Solicitud Reset Password'), ('create', 'Crear'), ('update_full', 'Actualización Completa'), ('update_partial', 'Actualización Parcial'), ('delete', 'Eliminar'), ('view', 'Ver Detalle'), ('list', 'Listar'), ('check_exists', 'Verificar Existencia'), ('options_request', 'Consulta de Opciones'), ('permission_change', 'Cambio de Permisos'), ('role_assign', 'Asignación de Rol'), ('role_remove', 'Remoción de Rol'), ('tenant_switch', 'Cambio de Tenant'), ('security_event', 'Evento de Seguridad'), ('system_action', 'Acción del Sistema'), ('loan_approve', 'Aprobación de Préstamo'), ('loan_reject', 'Rechazo de Préstamo'), ('client_activate', 'Activación de Cliente'), ('client_deactivate', 'Desactivación de Cliente'), ('subscription_change', 'Cambio de Suscripción')], help_text='Tipo de acción realizada', max_length=50),
        ),
    ]
