# Generated by Django 6.0.4 on 2026-05-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_update_action_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login_success', 'Login Exitoso'), ('login_failed', 'Login Fallido'), ('logout', 'Logout'), ('register', 'Registro'), ('password_reset_request', 'Solicitud Reset Password'), ('create', 'Crear'), ('update_full', 'Actualización Completa'), ('update_partial', 'Actualización Parcial'), ('delete', 'Eliminar'), ('view', 'Ver Detalle'), ('list', 'Listar'), ('check_exists', 'Verificar Existencia'), ('options_request', 'Consulta de Opciones'), ('permission_change', 'Cambio de Permisos'), ('role_assign', 'Asignación de Rol'), ('role_remove', 'Remoción de Rol'), ('tenant_switch', 'Cambio de Tenant'), ('security_event', 'Evento de Seguridad'), ('system_action', 'Acción del Sistema'), ('loan_approve', 'Aprobación de Préstamo'), ('loan_reject', 'Rechazo de Préstamo'), ('client_activate', 'Activación de Cliente'), ('client_deactivate', 'Desactivación de Cliente'), ('subscription_change', 'Cambio de Suscripción'), ('identity_verification_start', 'Verificación de Identidad Iniciada'), ('identity_verification_approved', 'Verificación de Identidad Aprobada'), ('identity_verification_declined', 'Verificación de Identidad Rechazada'), ('identity_verification_error', 'Error en Verificación de Identidad'), ('identity_verification_webhook', 'Webhook de Verificación de Identidad Recibido')], help_text='Tipo de acción realizada', max_length=50),
        ),
    ]
