# Generated by Django 6.0.4 on 2026-04-11 17:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
        ('tenants', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_number', models.CharField(help_text='Número único de identificación de la solicitud', max_length=50, unique=True, verbose_name='Número de Solicitud')),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto Solicitado')),
                ('term_months', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(360)], verbose_name='Plazo en Meses')),
                ('purpose', models.TextField(blank=True, verbose_name='Propósito del Crédito')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SUBMITTED', 'Enviada'), ('UNDER_REVIEW', 'En Revisión'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada'), ('DISBURSED', 'Desembolsada'), ('CANCELLED', 'Cancelada')], db_index=True, default='DRAFT', max_length=20, verbose_name='Estado')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Rechazo')),
                ('disbursed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Desembolso')),
                ('credit_score', models.IntegerField(blank=True, help_text='Score calculado (0-1000)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Score de Crédito')),
                ('risk_level', models.CharField(blank=True, choices=[('LOW', 'Bajo'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto'), ('VERY_HIGH', 'Muy Alto')], max_length=20, null=True, verbose_name='Nivel de Riesgo')),
                ('debt_to_income_ratio', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de deuda sobre ingreso', max_digits=5, null=True, verbose_name='Ratio Deuda/Ingreso')),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Aprobado')),
                ('approved_term_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Plazo Aprobado (meses)')),
                ('approved_interest_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Tasa anual en porcentaje', max_digits=5, null=True, verbose_name='Tasa de Interés Aprobada')),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Cuota Mensual')),
                ('notes', models.TextField(blank=True, verbose_name='Notas Internas')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo de Rechazo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_applications', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado Por')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='clients.client', verbose_name='Cliente')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='products.creditproduct', verbose_name='Producto Crediticio')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='Revisado Por')),
            ],
            options={
                'verbose_name': 'Solicitud de Crédito',
                'verbose_name_plural': 'Solicitudes de Crédito',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanApplicationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('is_internal', models.BooleanField(default=True, help_text='Si es interno, solo lo ven los empleados', verbose_name='Comentario Interno')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='loans.loanapplication', verbose_name='Solicitud')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_comments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Comentario de Solicitud',
                'verbose_name_plural': 'Comentarios de Solicitud',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('ID_DOCUMENT', 'Documento de Identidad'), ('INCOME_PROOF', 'Comprobante de Ingresos'), ('BANK_STATEMENT', 'Estado de Cuenta'), ('EMPLOYMENT_LETTER', 'Carta de Trabajo'), ('TAX_RETURN', 'Declaración de Impuestos'), ('PROPERTY_DEED', 'Escritura de Propiedad'), ('OTHER', 'Otro')], max_length=30, verbose_name='Tipo de Documento')),
                ('file', models.FileField(upload_to='loan_applications/%Y/%m/', verbose_name='Archivo')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nombre del Archivo')),
                ('file_size', models.PositiveIntegerField(help_text='Tamaño del archivo en bytes', verbose_name='Tamaño (bytes)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Verificación')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='loans.loanapplication', verbose_name='Solicitud')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_loan_documents', to=settings.AUTH_USER_MODEL, verbose_name='Subido Por')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_loan_documents', to=settings.AUTH_USER_MODEL, verbose_name='Verificado Por')),
            ],
            options={
                'verbose_name': 'Documento de Solicitud',
                'verbose_name_plural': 'Documentos de Solicitud',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['institution', 'status'], name='loans_loana_institu_eb1056_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['institution', 'client'], name='loans_loana_institu_8ac608_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['institution', 'product'], name='loans_loana_institu_1caa50_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['application_number'], name='loans_loana_applica_d0394f_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['submitted_at'], name='loans_loana_submitt_df5800_idx'),
        ),
    ]
