# Generated by Django 6.0.3 on 2026-05-03 21:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_add_cu11_fields_and_status_history'),
        ('clients', '0006_add_cu11_fields_and_status_history'),
        ('loans', '0001_initial'),
        ('tenants', '0002_tenantbranding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict, help_text='Información adicional en formato JSON', verbose_name='Datos Adicionales'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Personal interno asignado para revisar la solicitud', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_loan_applications', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_applications', to='branches.branch', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loan_applications', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='documents_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'No Requerida'), ('PENDING', 'Pendiente'), ('COMPLETE', 'Completa'), ('OBSERVED', 'Observada')], default='NOT_REQUIRED', max_length=20, verbose_name='Estado de Documentos'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='employment_description',
            field=models.TextField(blank=True, help_text='Detalles de la actividad laboral o económica', verbose_name='Descripción Laboral/Económica'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('EMPLOYED', 'Empleado en relación de dependencia'), ('SELF_EMPLOYED', 'Trabajador independiente'), ('BUSINESS_OWNER', 'Propietario de negocio'), ('RETIRED', 'Jubilado'), ('UNEMPLOYED', 'Desempleado'), ('STUDENT', 'Estudiante'), ('OTHER', 'Otro')], max_length=30, null=True, verbose_name='Tipo de Empleo'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='identity_verification_status',
            field=models.CharField(choices=[('NOT_VERIFIED', 'No Verificada'), ('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Progreso'), ('APPROVED', 'Aprobada'), ('DECLINED', 'Rechazada'), ('MANUAL_REVIEW', 'Revisión Manual')], db_index=True, default='NOT_VERIFIED', max_length=20, verbose_name='Estado de Verificación de Identidad'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='internal_notes',
            field=models.TextField(blank=True, verbose_name='Notas Internas Adicionales'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ingreso Mensual Aproximado'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='observation_reason',
            field=models.TextField(blank=True, help_text='Razón por la cual la solicitud fue observada', verbose_name='Motivo de Observación'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_loan_applications', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='clients.client', verbose_name='Cliente/Prestatario'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('SUBMITTED', 'Enviada'), ('IN_REVIEW', 'En Revisión'), ('OBSERVED', 'Observada'), ('UNDER_REVIEW', 'En Revisión Interna'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada'), ('DISBURSED', 'Desembolsada'), ('CANCELLED', 'Cancelada')], db_index=True, default='DRAFT', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='LoanApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_status', models.CharField(help_text='Estado anterior de la solicitud', max_length=20, verbose_name='Estado Anterior')),
                ('new_status', models.CharField(help_text='Nuevo estado de la solicitud', max_length=20, verbose_name='Nuevo Estado')),
                ('title', models.CharField(help_text='Título visible para el prestatario y staff', max_length=255, verbose_name='Título del Evento')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del cambio de estado', verbose_name='Descripción')),
                ('actor_role', models.CharField(blank=True, help_text='Rol del usuario que hizo el cambio', max_length=50, verbose_name='Rol del Actor')),
                ('is_visible_to_borrower', models.BooleanField(default=True, help_text='Si el evento es visible en el timeline del prestatario', verbose_name='Visible para Prestatario')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional en formato JSON', verbose_name='Metadata')),
                ('actor', models.ForeignKey(blank=True, help_text='Usuario que realizó el cambio de estado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes_made', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='loans.loanapplication', verbose_name='Solicitud')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
            ],
            options={
                'verbose_name': 'Historial de Estado de Solicitud',
                'verbose_name_plural': 'Historiales de Estados de Solicitudes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['institution', 'application'], name='loans_loana_institu_575904_idx'), models.Index(fields=['institution', 'created_at'], name='loans_loana_institu_32901c_idx'), models.Index(fields=['application', 'created_at'], name='loans_loana_applica_741a16_idx')],
            },
        ),
    ]
