# Generated by Django 6.0.4 on 2026-05-08 17:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_add_cu11_fields_and_status_history'),
        ('products', '0001_initial'),
        ('roles', '0001_initial'),
        ('storage', '0001_create_file_resource_model'),
        ('tenants', '0003_create_file_resource_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditProductParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Mínimo (Bs)')),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Máximo (Bs)')),
                ('min_term_months', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Plazo Mínimo (meses)')),
                ('max_term_months', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Plazo Máximo (meses)')),
                ('min_interest_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tasa Mínima (%)')),
                ('max_interest_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tasa Máxima (%)')),
                ('allowed_currencies', models.JSONField(default=list, help_text='["BOB", "USD"]', verbose_name='Monedas Permitidas')),
                ('payment_frequencies', models.JSONField(default=list, help_text='["MONTHLY", "BIWEEKLY", "WEEKLY"]', verbose_name='Frecuencias de Pago')),
                ('max_financing_percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Porcentaje Máximo de Financiamiento (%)')),
                ('requires_guarantor', models.BooleanField(default=False, verbose_name='Requiere Garante')),
                ('requires_collateral', models.BooleanField(default=False, verbose_name='Requiere Garantía Real')),
            ],
            options={
                'verbose_name': 'Parámetro de Producto',
                'verbose_name_plural': 'Parámetros de Productos',
                'db_table': 'credit_product_parameters',
            },
        ),
        migrations.CreateModel(
            name='DecisionThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_score_auto_approval', models.IntegerField(default=70, help_text='Score >= este valor → aprobación automática', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Score Mínimo para Aprobación Automática')),
                ('min_score_manual_review', models.IntegerField(default=50, help_text='Score entre este valor y auto_approval → revisión manual', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Score Mínimo para Revisión Manual')),
                ('max_score_auto_rejection', models.IntegerField(default=49, help_text='Score <= este valor → rechazo automático', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Score Máximo para Rechazo Automático')),
                ('max_amount_auto_approval', models.DecimalField(blank=True, decimal_places=2, help_text='Montos superiores requieren revisión manual', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Máximo para Aprobación Automática (Bs)')),
                ('requires_manager_approval_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Montos superiores requieren aprobación de gerente/comité', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto que Requiere Aprobación de Gerente (Bs)')),
            ],
            options={
                'verbose_name': 'Umbral de Decisión',
                'verbose_name_plural': 'Umbrales de Decisión',
                'db_table': 'decision_thresholds',
            },
        ),
        migrations.CreateModel(
            name='DocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(help_text='ID_DOCUMENT, INCOME_PROOF, BANK_STATEMENT, etc.', max_length=50, verbose_name='Tipo de Documento')),
                ('document_name', models.CharField(help_text='Nombre descriptivo para mostrar al cliente', max_length=200, verbose_name='Nombre del Documento')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del documento requerido', verbose_name='Descripción')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Si es obligatorio para aprobar la solicitud', verbose_name='Obligatorio')),
                ('max_validity_days', models.IntegerField(blank=True, help_text='Días de vigencia del documento (ej: 30 para DDRR)', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Vigencia Máxima (días)')),
                ('allowed_formats', models.JSONField(default=list, help_text='["application/pdf", "image/jpeg", "image/png"]', verbose_name='Formatos Permitidos')),
                ('max_file_size_mb', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Tamaño Máximo (MB)')),
                ('requires_manual_review', models.BooleanField(default=True, help_text='Si debe ser revisado por un analista', verbose_name='Requiere Revisión Manual')),
                ('display_order', models.IntegerField(default=0, verbose_name='Orden de Visualización')),
            ],
            options={
                'verbose_name': 'Requisito Documental',
                'verbose_name_plural': 'Requisitos Documentales',
                'db_table': 'document_requirements',
                'ordering': ['display_order', 'document_name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentReviewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('REQUESTED_REUPLOAD', 'Solicitó Re-carga')], max_length=20, verbose_name='Acción')),
                ('comments', models.TextField(blank=True, verbose_name='Comentarios')),
            ],
            options={
                'verbose_name': 'Historial de Revisión de Documento',
                'verbose_name_plural': 'Historiales de Revisión de Documentos',
                'db_table': 'document_review_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EligibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_debt_to_income_ratio', models.DecimalField(decimal_places=2, default=40.0, help_text='Relación Cuota-Ingreso máxima permitida (típicamente 40%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='RCI Máximo (%)')),
                ('min_income_required', models.DecimalField(decimal_places=2, help_text='Ingreso líquido mensual mínimo', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ingreso Mínimo Requerido (Bs)')),
                ('min_employment_months', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Antigüedad Laboral Mínima (meses)')),
                ('max_arrears_allowed', models.DecimalField(decimal_places=2, default=0, help_text='Monto máximo de mora activa permitido', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mora Máxima Permitida (Bs)')),
                ('allowed_cic_categories', models.JSONField(default=list, help_text='Lista de categorías CIC aceptadas: ["A", "B", "C"]', verbose_name='Categorías CIC Permitidas')),
                ('min_collateral_coverage', models.DecimalField(decimal_places=2, default=125.0, help_text='Valor garantía / Monto crédito (típicamente 125%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cobertura Mínima de Garantía (%)')),
                ('min_age', models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(18)], verbose_name='Edad Mínima')),
                ('max_age', models.IntegerField(default=70, validators=[django.core.validators.MinValueValidator(18)], verbose_name='Edad Máxima')),
            ],
            options={
                'verbose_name': 'Regla de Elegibilidad',
                'verbose_name_plural': 'Reglas de Elegibilidad',
                'db_table': 'eligibility_rules',
            },
        ),
        migrations.CreateModel(
            name='LoanApplicationDocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('UPLOADED', 'Cargado'), ('UNDER_REVIEW', 'En Revisión'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Carga')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo de Rechazo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Documento Requerido de Solicitud',
                'verbose_name_plural': 'Documentos Requeridos de Solicitudes',
                'db_table': 'loan_application_document_requirements',
                'ordering': ['document_requirement__display_order'],
            },
        ),
        migrations.CreateModel(
            name='RuleSetAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_type', models.CharField(choices=[('CREATED', 'Creado'), ('UPDATED', 'Actualizado'), ('ACTIVATED', 'Activado'), ('ARCHIVED', 'Archivado')], max_length=20, verbose_name='Tipo de Cambio')),
                ('field_name', models.CharField(blank=True, max_length=100, verbose_name='Campo Modificado')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='Valor Anterior')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='Valor Nuevo')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Auditoría de Reglas',
                'verbose_name_plural': 'Auditorías de Reglas',
                'db_table': 'rule_set_audits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(help_text='Ej: 1.0.0, 1.1.0, 2.0.0', max_length=20, verbose_name='Versión')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ACTIVE', 'Activa'), ('ARCHIVED', 'Archivada')], db_index=True, default='DRAFT', max_length=10, verbose_name='Estado')),
                ('name', models.CharField(help_text='Nombre descriptivo del conjunto de reglas', max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Activación')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Archivo')),
                ('notes', models.TextField(blank=True, help_text='Notas sobre cambios en esta versión', verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Conjunto de Reglas',
                'verbose_name_plural': 'Conjuntos de Reglas',
                'db_table': 'tenant_rule_sets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStageDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage_name', models.CharField(max_length=100, verbose_name='Nombre de la Etapa')),
                ('stage_code', models.CharField(help_text='DRAFT, SUBMITTED, DOCUMENTS, KYC, SCORING, REVIEW, APPROVED, etc.', max_length=50, verbose_name='Código de la Etapa')),
                ('stage_order', models.IntegerField(help_text='Orden secuencial de la etapa', verbose_name='Orden')),
                ('time_limit_hours', models.IntegerField(blank=True, help_text='Tiempo máximo para completar la etapa', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Tiempo Límite (horas)')),
                ('is_automated', models.BooleanField(default=False, help_text='Si la etapa se ejecuta automáticamente', verbose_name='Automatizada')),
                ('escalation_rules', models.JSONField(blank=True, default=dict, help_text='Configuración de escalamiento por timeout', verbose_name='Reglas de Escalamiento')),
            ],
            options={
                'verbose_name': 'Definición de Etapa de Workflow',
                'verbose_name_plural': 'Definiciones de Etapas de Workflow',
                'db_table': 'workflow_stage_definitions',
                'ordering': ['stage_order'],
            },
        ),
        migrations.AddField(
            model_name='loanapplicationstatushistory',
            name='action_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Acción Completada'),
        ),
        migrations.AddField(
            model_name='loanapplicationstatushistory',
            name='action_description',
            field=models.TextField(blank=True, help_text='Descripción de la acción que debe realizar el cliente', verbose_name='Descripción de Acción'),
        ),
        migrations.AddField(
            model_name='loanapplicationstatushistory',
            name='action_url',
            field=models.CharField(blank=True, help_text='URL a la que debe ir el cliente para completar la acción', max_length=500, verbose_name='URL de Acción'),
        ),
        migrations.AddField(
            model_name='loanapplicationstatushistory',
            name='client_message',
            field=models.TextField(blank=True, help_text='Mensaje amigable para mostrar al cliente en el timeline', verbose_name='Mensaje para Cliente'),
        ),
        migrations.AddField(
            model_name='loanapplicationstatushistory',
            name='notification_sent',
            field=models.BooleanField(default=False, help_text='Si se envió notificación al cliente', verbose_name='Notificación Enviada'),
        ),
        migrations.AddField(
            model_name='loanapplicationstatushistory',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío de Notificación'),
        ),
        migrations.AddField(
            model_name='loanapplicationstatushistory',
            name='requires_client_action',
            field=models.BooleanField(default=False, help_text='Si el cliente debe realizar alguna acción', verbose_name='Requiere Acción del Cliente'),
        ),
        migrations.AddIndex(
            model_name='loanapplicationstatushistory',
            index=models.Index(fields=['is_visible_to_borrower'], name='loans_loana_is_visi_416dbf_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplicationstatushistory',
            index=models.Index(fields=['requires_client_action', 'action_completed_at'], name='loans_loana_require_334074_idx'),
        ),
        migrations.AddField(
            model_name='creditproductparameter',
            name='institution',
            field=models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution'),
        ),
        migrations.AddField(
            model_name='creditproductparameter',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_parameters', to='products.creditproduct', verbose_name='Producto Crediticio'),
        ),
        migrations.AddField(
            model_name='decisionthreshold',
            name='institution',
            field=models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution'),
        ),
        migrations.AddField(
            model_name='documentrequirement',
            name='institution',
            field=models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution'),
        ),
        migrations.AddField(
            model_name='documentrequirement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requirements', to='products.creditproduct', verbose_name='Producto Crediticio'),
        ),
        migrations.AddField(
            model_name='documentreviewhistory',
            name='file_resource_at_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.fileresource', verbose_name='Archivo al Momento de Revisión'),
        ),
        migrations.AddField(
            model_name='documentreviewhistory',
            name='institution',
            field=models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution'),
        ),
        migrations.AddField(
            model_name='documentreviewhistory',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Revisado Por'),
        ),
        migrations.AddField(
            model_name='eligibilityrule',
            name='institution',
            field=models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution'),
        ),
        migrations.AddField(
            model_name='loanapplicationdocumentrequirement',
            name='document_requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_requirements', to='loans.documentrequirement', verbose_name='Requisito Documental'),
        ),
        migrations.AddField(
            model_name='loanapplicationdocumentrequirement',
            name='file_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_documents', to='storage.fileresource', verbose_name='Archivo'),
        ),
        migrations.AddField(
            model_name='loanapplicationdocumentrequirement',
            name='institution',
            field=models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution'),
        ),
        migrations.AddField(
            model_name='loanapplicationdocumentrequirement',
            name='loan_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_checklist', to='loans.loanapplication', verbose_name='Solicitud de Crédito'),
        ),
        migrations.AddField(
            model_name='loanapplicationdocumentrequirement',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL, verbose_name='Revisado Por'),
        ),
        migrations.AddField(
            model_name='loanapplicationdocumentrequirement',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Cargado Por'),
        ),
        migrations.AddField(
            model_name='documentreviewhistory',
            name='document_requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_history', to='loans.loanapplicationdocumentrequirement', verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='rulesetaudit',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_changes', to=settings.AUTH_USER_MODEL, verbose_name='Modificado Por'),
        ),
        migrations.AddField(
            model_name='rulesetaudit',
            name='institution',
            field=models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution'),
        ),
        migrations.AddField(
            model_name='tenantruleset',
            name='activated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_rule_sets', to=settings.AUTH_USER_MODEL, verbose_name='Activado Por'),
        ),
        migrations.AddField(
            model_name='tenantruleset',
            name='institution',
            field=models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution'),
        ),
        migrations.AddField(
            model_name='rulesetaudit',
            name='rule_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='loans.tenantruleset', verbose_name='Conjunto de Reglas'),
        ),
        migrations.AddField(
            model_name='eligibilityrule',
            name='rule_set',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_rule', to='loans.tenantruleset', verbose_name='Conjunto de Reglas'),
        ),
        migrations.AddField(
            model_name='documentrequirement',
            name='rule_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requirements', to='loans.tenantruleset', verbose_name='Conjunto de Reglas'),
        ),
        migrations.AddField(
            model_name='decisionthreshold',
            name='rule_set',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision_threshold', to='loans.tenantruleset', verbose_name='Conjunto de Reglas'),
        ),
        migrations.AddField(
            model_name='creditproductparameter',
            name='rule_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_parameters', to='loans.tenantruleset', verbose_name='Conjunto de Reglas'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='rule_set_snapshot',
            field=models.ForeignKey(blank=True, help_text='Snapshot del conjunto de reglas activo al momento de crear la solicitud', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='loans.tenantruleset', verbose_name='Conjunto de Reglas (Snapshot)'),
        ),
        migrations.AddField(
            model_name='workflowstagedefinition',
            name='institution',
            field=models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution'),
        ),
        migrations.AddField(
            model_name='workflowstagedefinition',
            name='responsible_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_stages', to='roles.role', verbose_name='Rol Responsable'),
        ),
        migrations.AddField(
            model_name='workflowstagedefinition',
            name='rule_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_stages', to='loans.tenantruleset', verbose_name='Conjunto de Reglas'),
        ),
        migrations.AddIndex(
            model_name='loanapplicationdocumentrequirement',
            index=models.Index(fields=['loan_application', 'status'], name='loan_applic_loan_ap_f60378_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplicationdocumentrequirement',
            index=models.Index(fields=['status', 'reviewed_at'], name='loan_applic_status_f05c1b_idx'),
        ),
        migrations.AddConstraint(
            model_name='loanapplicationdocumentrequirement',
            constraint=models.UniqueConstraint(fields=('loan_application', 'document_requirement'), name='unique_doc_per_application'),
        ),
        migrations.AddIndex(
            model_name='documentreviewhistory',
            index=models.Index(fields=['document_requirement', 'created_at'], name='document_re_documen_a6cdb8_idx'),
        ),
        migrations.AddIndex(
            model_name='documentreviewhistory',
            index=models.Index(fields=['reviewed_by', 'created_at'], name='document_re_reviewe_0c7ccc_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantruleset',
            index=models.Index(fields=['institution', 'status'], name='tenant_rule_institu_04abf8_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantruleset',
            index=models.Index(fields=['institution', 'version'], name='tenant_rule_institu_49f669_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantruleset',
            constraint=models.UniqueConstraint(fields=('institution', 'version'), name='unique_version_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='tenantruleset',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('institution',), name='unique_active_rule_set_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='rulesetaudit',
            index=models.Index(fields=['rule_set', 'created_at'], name='rule_set_au_rule_se_1aa60a_idx'),
        ),
        migrations.AddIndex(
            model_name='rulesetaudit',
            index=models.Index(fields=['changed_by', 'created_at'], name='rule_set_au_changed_28defe_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrequirement',
            index=models.Index(fields=['rule_set', 'product'], name='document_re_rule_se_6f9da4_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrequirement',
            index=models.Index(fields=['document_type'], name='document_re_documen_092ffc_idx'),
        ),
        migrations.AddConstraint(
            model_name='creditproductparameter',
            constraint=models.UniqueConstraint(fields=('rule_set', 'product'), name='unique_product_per_rule_set'),
        ),
        migrations.AddConstraint(
            model_name='workflowstagedefinition',
            constraint=models.UniqueConstraint(fields=('rule_set', 'stage_code'), name='unique_stage_per_rule_set'),
        ),
    ]
