# Generated by Django 6.0.4 on 2026-05-08 18:10

from django.db import migrations


def create_custom_permissions(apps, schema_editor):
    """
    Crea permisos personalizados para el módulo de créditos.
    """
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    # Obtener content type de LoanApplication
    try:
        loan_ct = ContentType.objects.get(app_label='loans', model='loanapplication')
    except ContentType.DoesNotExist:
        # Si no existe, crear uno temporal
        loan_ct = ContentType.objects.create(
            app_label='loans',
            model='loanapplication'
        )
    
    # Definir permisos personalizados
    permissions = [
        {
            'codename': 'manage_credit_rules',
            'name': 'Can manage credit rules and parameters',
        },
        {
            'codename': 'review_loan_documents',
            'name': 'Can review and approve loan documents',
        },
        {
            'codename': 'view_all_applications',
            'name': 'Can view all loan applications',
        },
        {
            'codename': 'manage_applications',
            'name': 'Can manage loan applications',
        },
        {
            'codename': 'view_applications',
            'name': 'Can view loan applications',
        },
    ]
    
    # Crear permisos
    for perm_data in permissions:
        Permission.objects.get_or_create(
            codename=perm_data['codename'],
            content_type=loan_ct,
            defaults={'name': perm_data['name']}
        )


def remove_custom_permissions(apps, schema_editor):
    """
    Elimina los permisos personalizados (rollback).
    """
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    try:
        loan_ct = ContentType.objects.get(app_label='loans', model='loanapplication')
        
        # Eliminar permisos personalizados
        Permission.objects.filter(
            content_type=loan_ct,
            codename__in=[
                'manage_credit_rules',
                'review_loan_documents',
                'view_all_applications',
                'manage_applications',
                'view_applications',
            ]
        ).delete()
    except ContentType.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_creditproductparameter_decisionthreshold_and_more'),
        ('contenttypes', '__latest__'),
        ('auth', '__latest__'),
    ]

    operations = [
        migrations.RunPython(
            create_custom_permissions,
            reverse_code=remove_custom_permissions
        ),
    ]
