# Generated by Django 6.0.4 on 2026-05-09 23:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_add_workflow_dynamic_fields'),
        ('tenants', '0003_create_file_resource_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstagedefinition',
            name='escalation_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Configuración de escalamiento por timeout. Ej: {"notify_supervisor": true, "escalate_to_role": "SUPERVISOR", "escalation_message": "..."}', verbose_name='Reglas de Escalamiento'),
        ),
        migrations.CreateModel(
            name='AmortizationSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Código único (ej: FRENCH, GERMAN)', max_length=50, verbose_name='Código')),
                ('name', models.CharField(help_text='Nombre del sistema', max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, help_text='Descripción del método de cálculo', verbose_name='Descripción')),
                ('formula_type', models.CharField(help_text='Identificador del algoritmo de cálculo', max_length=50, verbose_name='Tipo de Fórmula')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('display_order', models.IntegerField(default=0, verbose_name='Orden de Visualización')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
            ],
            options={
                'verbose_name': 'Sistema de Amortización',
                'verbose_name_plural': 'Sistemas de Amortización',
                'db_table': 'amortization_systems',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['institution', 'is_active'], name='amortizatio_institu_593e56_idx')],
                'constraints': [models.UniqueConstraint(fields=('institution', 'code'), name='unique_amortization_system_code_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Código ISO 4217 (ej: BOB, USD, EUR)', max_length=3, verbose_name='Código ISO')),
                ('name', models.CharField(help_text='Nombre de la moneda', max_length=100, verbose_name='Nombre')),
                ('symbol', models.CharField(help_text='Símbolo de la moneda (ej: Bs, $, €)', max_length=10, verbose_name='Símbolo')),
                ('exchange_rate_to_base', models.DecimalField(decimal_places=4, default=1.0, help_text='Tipo de cambio respecto a la moneda base (BOB)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Tipo de Cambio a Moneda Base')),
                ('is_base_currency', models.BooleanField(default=False, help_text='Indica si es la moneda base del sistema', verbose_name='Moneda Base')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('display_order', models.IntegerField(default=0, verbose_name='Orden de Visualización')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'db_table': 'currencies',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['institution', 'is_active'], name='currencies_institu_634ab0_idx')],
                'constraints': [models.UniqueConstraint(fields=('institution', 'code'), name='unique_currency_code_per_tenant'), models.UniqueConstraint(condition=models.Q(('is_base_currency', True)), fields=('institution',), name='unique_base_currency_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Código único del tipo de documento (ej: ID_DOCUMENT)', max_length=50, verbose_name='Código')),
                ('name', models.CharField(help_text='Nombre descriptivo del documento', max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del documento', verbose_name='Descripción')),
                ('category', models.CharField(choices=[('IDENTITY', 'Identificación'), ('FINANCIAL', 'Financiero'), ('LEGAL', 'Legal'), ('COLLATERAL', 'Garantías'), ('OTHER', 'Otros')], default='OTHER', max_length=20, verbose_name='Categoría')),
                ('default_formats', models.JSONField(default=list, help_text='["PDF", "JPG", "PNG"]', verbose_name='Formatos Permitidos por Defecto')),
                ('default_max_size_mb', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Tamaño Máximo por Defecto (MB)')),
                ('default_validity_days', models.IntegerField(blank=True, help_text='Días de validez del documento', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Validez por Defecto (días)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('display_order', models.IntegerField(default=0, verbose_name='Orden de Visualización')),
                ('icon', models.CharField(blank=True, help_text='Nombre del ícono de lucide-react', max_length=50, verbose_name='Ícono')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'db_table': 'document_types',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['institution', 'is_active'], name='document_ty_institu_3d4fa2_idx'), models.Index(fields=['category'], name='document_ty_categor_f3d407_idx')],
                'constraints': [models.UniqueConstraint(fields=('institution', 'code'), name='unique_document_type_code_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='PaymentFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Código único (ej: MONTHLY, BIWEEKLY)', max_length=50, verbose_name='Código')),
                ('name', models.CharField(help_text='Nombre descriptivo (ej: Mensual, Quincenal)', max_length=200, verbose_name='Nombre')),
                ('days_between_payments', models.IntegerField(help_text='Número de días entre cada pago', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Días entre Pagos')),
                ('payments_per_year', models.IntegerField(help_text='Cantidad de pagos en un año', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Pagos por Año')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('display_order', models.IntegerField(default=0, verbose_name='Orden de Visualización')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
            ],
            options={
                'verbose_name': 'Frecuencia de Pago',
                'verbose_name_plural': 'Frecuencias de Pago',
                'db_table': 'payment_frequencies',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['institution', 'is_active'], name='payment_fre_institu_b85752_idx')],
                'constraints': [models.UniqueConstraint(fields=('institution', 'code'), name='unique_payment_frequency_code_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Código único del tipo (ej: PERSONAL, VEHICULAR)', max_length=50, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('category', models.CharField(choices=[('CONSUMER', 'Consumo'), ('COMMERCIAL', 'Comercial'), ('MORTGAGE', 'Hipotecario'), ('AGRICULTURAL', 'Agropecuario')], max_length=20, verbose_name='Categoría Principal')),
                ('icon', models.CharField(blank=True, help_text='Nombre del ícono de lucide-react', max_length=50, verbose_name='Ícono')),
                ('color', models.CharField(blank=True, help_text='Color para UI (ej: blue, green, purple)', max_length=20, verbose_name='Color')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('display_order', models.IntegerField(default=0, verbose_name='Orden de Visualización')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
            ],
            options={
                'verbose_name': 'Tipo de Producto',
                'verbose_name_plural': 'Tipos de Productos',
                'db_table': 'product_types',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['institution', 'is_active'], name='product_typ_institu_a21ea8_idx'), models.Index(fields=['category'], name='product_typ_categor_a17744_idx')],
                'constraints': [models.UniqueConstraint(fields=('institution', 'code'), name='unique_product_type_code_per_tenant')],
            },
        ),
    ]
