# Generated by Django 6.0.4 on 2026-05-10 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0012_remove_document_requirement_model'),
        ('products', '0003_add_ruleset_and_documents'),
        ('storage', '0001_create_file_resource_model'),
        ('tenants', '0003_create_file_resource_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='creditproductparameter_allowed_amortization_systems',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='creditproductparameter_allowed_amortization_systems',
            name='amortizationsystem',
        ),
        migrations.RemoveField(
            model_name='creditproductparameter_allowed_amortization_systems',
            name='creditproductparameter',
        ),
        migrations.AlterUniqueTogether(
            name='creditproductparameter_allowed_currencies',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='creditproductparameter_allowed_currencies',
            name='creditproductparameter',
        ),
        migrations.RemoveField(
            model_name='creditproductparameter_allowed_currencies',
            name='currency',
        ),
        migrations.AlterUniqueTogether(
            name='creditproductparameter_allowed_payment_frequencies',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='creditproductparameter_allowed_payment_frequencies',
            name='creditproductparameter',
        ),
        migrations.RemoveField(
            model_name='creditproductparameter_allowed_payment_frequencies',
            name='paymentfrequency',
        ),
        migrations.AlterModelOptions(
            name='creditproductparameter',
            options={'ordering': ['rule_set__version'], 'verbose_name': 'Parámetro de Producto', 'verbose_name_plural': 'Parámetros de Productos'},
        ),
        migrations.AlterModelOptions(
            name='loanapplicationdocumentrequirement',
            options={'ordering': ['product_document_requirement__display_order'], 'verbose_name': 'Documento Requerido de Solicitud', 'verbose_name_plural': 'Documentos Requeridos de Solicitudes'},
        ),
        migrations.RunSQL(
            sql="ALTER TABLE loan_application_document_requirements DROP CONSTRAINT IF EXISTS unique_doc_per_application",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RemoveIndex(
            model_name='creditproductparameter',
            name='credit_prod_rule_se_idx',
        ),
        migrations.RenameIndex(
            model_name='creditproductparameter',
            new_name='credit_prod_rule_se_acb76c_idx',
            old_name='credit_product_parameters_rule_set_idx',
        ),
        migrations.AddField(
            model_name='creditproductparameter',
            name='allowed_amortization_systems',
            field=models.ManyToManyField(blank=True, related_name='product_parameters', to='loans.amortizationsystem', verbose_name='Sistemas de Amortización Permitidos'),
        ),
        migrations.AddField(
            model_name='creditproductparameter',
            name='allowed_payment_frequencies',
            field=models.ManyToManyField(blank=True, related_name='product_parameters', to='loans.paymentfrequency', verbose_name='Frecuencias de Pago Permitidas'),
        ),
        migrations.AddField(
            model_name='loanapplicationdocumentrequirement',
            name='product_document_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application_requirements', to='products.productdocumentrequirement', verbose_name='Documento Requerido del Producto'),
        ),
        migrations.AddConstraint(
            model_name='loanapplicationdocumentrequirement',
            constraint=models.UniqueConstraint(fields=('loan_application', 'product_document_requirement'), name='unique_doc_per_application'),
        ),
        migrations.DeleteModel(
            name='CreditProductParameter_allowed_amortization_systems',
        ),
        migrations.DeleteModel(
            name='CreditProductParameter_allowed_currencies',
        ),
        migrations.DeleteModel(
            name='CreditProductParameter_allowed_payment_frequencies',
        ),
        migrations.RemoveField(
            model_name='creditproductparameter',
            name='payment_frequencies',
        ),
        migrations.RemoveField(
            model_name='creditproductparameter',
            name='allowed_currencies',
        ),
        migrations.AddField(
            model_name='creditproductparameter',
            name='allowed_currencies',
            field=models.ManyToManyField(blank=True, related_name='product_parameters', to='loans.currency', verbose_name='Monedas Permitidas'),
        ),
    ]
