# Generated by Django 6.0.4 on 2026-05-10 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0013_add_product_document_requirement_field'),
        ('products', '0004_add_product_document_requirement_field'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE loan_application_document_requirements DROP CONSTRAINT IF EXISTS unique_doc_per_application",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.AlterField(
            model_name='loanapplicationdocumentrequirement',
            name='product_document_requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_requirements', to='products.productdocumentrequirement', verbose_name='Documento Requerido del Producto'),
        ),
    ]
