# Generated by Django 6.0.4 on 2026-05-10 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0014_make_product_document_requirement_required'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='loanapplicationdocumentrequirement',
            name='unique_doc_per_application',
        ),
    ]
