# Generated by Django 6.0.4 on 2026-05-12 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0015_add_product_selections'),
        ('products', '0005_add_product_selections'),
        ('storage', '0001_create_file_resource_model'),
        ('tenants', '0003_create_file_resource_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='loanapplicationdocumentrequirement',
            constraint=models.UniqueConstraint(fields=('loan_application', 'product_document_requirement'), name='unique_doc_per_application'),
        ),
    ]
