# Generated by Django 6.0.4 on 2026-05-16 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0013_refactor_loan_app_doc_requirement'),
        ('loans', '0016_loanapplicationdocumentrequirement_unique_doc_per_application'),
    ]

    operations = [
    ]
