# Generated by Django 6.0.4 on 2026-05-30 19:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0017_merge_20260516_0303'),
        ('tenants', '0003_create_file_resource_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado En')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado En')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido'), ('CANCELLED', 'Cancelado')], default='IN_PROGRESS', max_length=20, verbose_name='Estado')),
                ('total_stages_completed', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Etapas Completadas')),
                ('total_time_seconds', models.IntegerField(default=0, help_text='Tiempo total desde inicio hasta completado', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiempo Total (segundos)')),
                ('execution_data', models.JSONField(blank=True, default=dict, help_text='Datos adicionales del flujo (variables, contexto, etc.)', verbose_name='Datos de Ejecución')),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_executions', to='loans.workflowstagedefinition', verbose_name='Etapa Actual')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
                ('loan_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_execution', to='loans.loanapplication', verbose_name='Solicitud de Crédito')),
                ('rule_set', models.ForeignKey(help_text='Snapshot del workflow usado (inmutable durante la ejecución)', on_delete=django.db.models.deletion.PROTECT, related_name='workflow_executions', to='loans.tenantruleset', verbose_name='Conjunto de Reglas')),
            ],
            options={
                'verbose_name': 'Ejecución de Workflow',
                'verbose_name_plural': 'Ejecuciones de Workflow',
                'db_table': 'workflow_executions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStageExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_at', models.DateTimeField(auto_now_add=True, verbose_name='Entrada En')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado En')),
                ('time_spent_seconds', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiempo Gastado (segundos)')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completado'), ('SKIPPED', 'Omitido'), ('FAILED', 'Fallido')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('outcome', models.CharField(blank=True, choices=[('SUCCESS', 'Éxito'), ('FAILURE', 'Fallo'), ('TIMEOUT', 'Timeout'), ('CANCELLED', 'Cancelado')], max_length=20, null=True, verbose_name='Resultado')),
                ('is_escalated', models.BooleanField(default=False, verbose_name='Escalado')),
                ('escalated_at', models.DateTimeField(blank=True, null=True, verbose_name='Escalado En')),
                ('escalation_reason', models.TextField(blank=True, verbose_name='Motivo de Escalamiento')),
                ('decision_notes', models.TextField(blank=True, verbose_name='Notas de Decisión')),
                ('decision_data', models.JSONField(blank=True, default=dict, help_text='Datos adicionales de la decisión (condiciones, observaciones, etc.)', verbose_name='Datos de Decisión')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_stage_executions', to=settings.AUTH_USER_MODEL, verbose_name='Asignado A')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_stage_executions', to=settings.AUTH_USER_MODEL, verbose_name='Completado Por')),
                ('escalated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_stage_executions', to=settings.AUTH_USER_MODEL, verbose_name='Escalado A')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
                ('stage_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_executions', to='loans.workflowstagedefinition', verbose_name='Definición de Etapa')),
                ('workflow_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_executions', to='loans.workflowexecution', verbose_name='Ejecución de Workflow')),
            ],
            options={
                'verbose_name': 'Ejecución de Etapa',
                'verbose_name_plural': 'Ejecuciones de Etapas',
                'db_table': 'workflow_stage_executions',
                'ordering': ['entered_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('RETURNED', 'Devuelto'), ('ESCALATED', 'Escalado'), ('OBSERVED', 'Observado')], max_length=20, verbose_name='Decisión')),
                ('decided_at', models.DateTimeField(auto_now_add=True, verbose_name='Decidido En')),
                ('reason', models.TextField(help_text='Motivo de la decisión', verbose_name='Motivo')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales', verbose_name='Notas')),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Aprobado')),
                ('approved_term_months', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Plazo Aprobado (meses)')),
                ('approved_interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tasa de Interés Aprobada (%)')),
                ('conditions', models.JSONField(blank=True, default=list, help_text='Lista de condiciones especiales de la aprobación', verbose_name='Condiciones Especiales')),
                ('decision_metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales de la decisión (score, análisis, etc.)', verbose_name='Metadata de Decisión')),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_decisions_made', to=settings.AUTH_USER_MODEL, verbose_name='Decidido Por')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_decisions', to='loans.loanapplication', verbose_name='Solicitud de Crédito')),
                ('stage_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='loans.workflowstageexecution', verbose_name='Ejecución de Etapa')),
            ],
            options={
                'verbose_name': 'Decisión de Aprobación',
                'verbose_name_plural': 'Decisiones de Aprobación',
                'db_table': 'approval_decisions',
                'ordering': ['-decided_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['loan_application'], name='workflow_ex_loan_ap_2b8dd5_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['status', 'started_at'], name='workflow_ex_status_a792ab_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['current_stage'], name='workflow_ex_current_34750c_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowstageexecution',
            index=models.Index(fields=['workflow_execution', 'entered_at'], name='workflow_st_workflo_c70118_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowstageexecution',
            index=models.Index(fields=['status', 'entered_at'], name='workflow_st_status_fd1cca_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowstageexecution',
            index=models.Index(fields=['assigned_to', 'status'], name='workflow_st_assigne_759a55_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowstageexecution',
            index=models.Index(fields=['is_escalated', 'escalated_at'], name='workflow_st_is_esca_de317b_idx'),
        ),
        migrations.AddIndex(
            model_name='approvaldecision',
            index=models.Index(fields=['loan_application', 'decided_at'], name='approval_de_loan_ap_4b7a4e_idx'),
        ),
        migrations.AddIndex(
            model_name='approvaldecision',
            index=models.Index(fields=['decided_by', 'decided_at'], name='approval_de_decided_ba4f4b_idx'),
        ),
        migrations.AddIndex(
            model_name='approvaldecision',
            index=models.Index(fields=['decision', 'decided_at'], name='approval_de_decisio_c55f4b_idx'),
        ),
        migrations.AddIndex(
            model_name='approvaldecision',
            index=models.Index(fields=['stage_execution'], name='approval_de_stage_e_652a76_idx'),
        ),
    ]
