# Generated by Django 6.0.4 on 2026-05-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0017_merge_20260516_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='contract_generated',
            field=models.BooleanField(default=False, help_text='Indica si se ha generado un contrato para esta solicitud', verbose_name='Contrato Generado'),
        ),
    ]
