# Generated by Django 6.0.2 on 2026-05-31 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0018_loanapplication_contract_generated'),
        ('loans', '0018_workflowexecution_workflowstageexecution_and_more'),
    ]

    operations = [
    ]
