# Generated by Django 6.0.4 on 2026-05-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0019_rejectionreason'),
        ('tenants', '0003_create_file_resource_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejectionreason',
            name='code',
            field=models.CharField(help_text='Código único del motivo (ej: INSUFFICIENT_INCOME)', max_length=50, verbose_name='Código'),
        ),
        migrations.AddConstraint(
            model_name='rejectionreason',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='unique_institution_rejection_code'),
        ),
    ]
