# Generated by Django 6.0.4 on 2026-05-31 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0019_merge_20260531_0058'),
        ('tenants', '0003_create_file_resource_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único del motivo (ej: INSUFFICIENT_INCOME)', max_length=50, verbose_name='Código')),
                ('name', models.CharField(help_text='Nombre descriptivo del motivo', max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del motivo', verbose_name='Descripción')),
                ('category', models.CharField(choices=[('FINANCIAL', 'Financiero'), ('DOCUMENTATION', 'Documentación'), ('CREDIT_HISTORY', 'Historial Crediticio'), ('POLICY', 'Política'), ('RISK', 'Riesgo'), ('OTHER', 'Otro')], default='OTHER', max_length=50, verbose_name='Categoría')),
                ('is_active', models.BooleanField(default=True, help_text='Si está activo para ser seleccionado', verbose_name='Activo')),
                ('display_order', models.IntegerField(default=0, help_text='Orden en que aparece en la lista', verbose_name='Orden de Visualización')),
                ('requires_notes', models.BooleanField(default=False, help_text='Si requiere que el analista agregue notas adicionales', verbose_name='Requiere Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
            ],
            options={
                'verbose_name': 'Motivo de Rechazo',
                'verbose_name_plural': 'Motivos de Rechazo',
                'db_table': 'loans_rejection_reason',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='rejectionreason',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='unique_institution_rejection_code'),
        ),
    ]
