# Generated by Django 6.0.2 on 2026-05-31 06:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0020_rejectionreason'),
        ('tenants', '0003_create_file_resource_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditBureauQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('INFOCORP', 'Infocorp'), ('SENTINEL', 'Sentinel'), ('EQUIFAX', 'Equifax'), ('CIC', 'CIC (Central de Información Crediticia)'), ('SIMULATED', 'Simulado')], max_length=20, verbose_name='Proveedor')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SUCCESS', 'Exitosa'), ('FAILED', 'Fallida'), ('TIMEOUT', 'Time Out')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('query_data', models.JSONField(default=dict, help_text='Parámetros enviados al buró', verbose_name='Datos de la consulta')),
                ('response_data', models.JSONField(default=dict, help_text='Respuesta completa del proveedor', verbose_name='Respuesta del buró')),
                ('score_external', models.IntegerField(blank=True, help_text='Score reportado por el buró', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='Score Externo')),
                ('debt_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Deuda Total Reportada')),
                ('has_defaults', models.BooleanField(blank=True, null=True, verbose_name='Tiene Moras/Defaults')),
                ('default_details', models.JSONField(blank=True, default=dict, verbose_name='Detalles de Mora')),
                ('cic_category', models.CharField(blank=True, max_length=5, null=True, verbose_name='Categoría CIC')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('queried_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Consulta')),
                ('response_time_ms', models.IntegerField(blank=True, null=True, verbose_name='Tiempo de Respuesta (ms)')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bureau_queries', to='loans.loanapplication', verbose_name='Solicitud')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
            ],
            options={
                'verbose_name': 'Consulta a Buró de Crédito',
                'verbose_name_plural': 'Consultas a Buró de Crédito',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application', 'provider'], name='loans_credi_applica_669c6b_idx'), models.Index(fields=['status'], name='loans_credi_status_0530fa_idx')],
            },
        ),
        migrations.CreateModel(
            name='CreditEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Progreso'), ('COMPLETED', 'Completada'), ('FAILED', 'Fallida')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('score_ia', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Score IA (0-1000)')),
                ('score_bureau', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='Score Buró')),
                ('score_weighted', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Score Ponderado Final')),
                ('payment_capacity_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Capacidad de Pago (0-100)')),
                ('employment_stability_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Estabilidad Laboral (0-100)')),
                ('credit_history_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Historial Crediticio (0-100)')),
                ('debt_burden_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Carga Deuda (0-100)')),
                ('demographic_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Perfil Demográfico (0-100)')),
                ('dti_calculated', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='DTI Calculado (%)')),
                ('recommended_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Recomendado')),
                ('max_affordable_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Cuota Máxima Asequible')),
                ('features_used', models.JSONField(blank=True, default=dict, help_text='Variables de entrada utilizadas para la predicción', verbose_name='Features del Modelo')),
                ('model_version', models.CharField(blank=True, help_text='Versión del modelo ML utilizado', max_length=50, verbose_name='Versión del Modelo')),
                ('model_metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional del modelo (features importances, thresholds, etc.)', verbose_name='Metadata del Modelo')),
                ('eligibility_check_passed', models.BooleanField(blank=True, null=True, verbose_name='Reglas de Elegibilidad OK')),
                ('bureau_check_passed', models.BooleanField(blank=True, null=True, verbose_name='Buró OK')),
                ('auto_decision', models.CharField(blank=True, choices=[('APPROVE', 'Aprobar'), ('REJECT', 'Rechazar'), ('MANUAL_REVIEW', 'Revisión Manual'), ('ESCALATE', 'Escalar a Gerente')], max_length=20, null=True, verbose_name='Decisión Automática')),
                ('auto_decision_reason', models.TextField(blank=True, verbose_name='Razón de Decisión Automática')),
                ('evaluated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Evaluación')),
                ('evaluation_time_ms', models.IntegerField(blank=True, null=True, verbose_name='Tiempo de Evaluación (ms)')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_evaluation', to='loans.loanapplication', verbose_name='Solicitud')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
            ],
            options={
                'verbose_name': 'Evaluación Crediticia',
                'verbose_name_plural': 'Evaluaciones Crediticias',
                'indexes': [models.Index(fields=['application'], name='loans_credi_applica_d901fc_idx'), models.Index(fields=['status'], name='loans_credi_status_5c83b5_idx'), models.Index(fields=['score_weighted'], name='loans_credi_score_w_8e31c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModelRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=50, unique=True, verbose_name='Versión')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('TRAINING', 'Entrenando'), ('ACTIVE', 'Activo'), ('DEPRECATED', 'Deprecado'), ('FAILED', 'Fallido')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('algorithm', models.CharField(default='GradientBoosting', max_length=100, verbose_name='Algoritmo')),
                ('metrics', models.JSONField(default=dict, verbose_name='Métricas (precision, recall, f1)')),
                ('feature_names', models.JSONField(default=list, verbose_name='Nombres de Features')),
                ('feature_importances', models.JSONField(default=dict, verbose_name='Importancia de Features')),
                ('training_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrenamiento')),
                ('training_samples', models.IntegerField(blank=True, null=True, verbose_name='Muestras de Entrenamiento')),
                ('model_path', models.CharField(blank=True, max_length=500, verbose_name='Ruta del Modelo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
            ],
            options={
                'verbose_name': 'Registro de Modelo',
                'verbose_name_plural': 'Registros de Modelos',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_model')],
            },
        ),
    ]
