# Generated by Django 6.0.4 on 2026-05-31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_add_cu11_fields_and_status_history'),
        ('loans', '0022_activecredit_creditgraceperiod_creditinstallment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditSupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('institution', models.ForeignKey(db_column='institution_id', on_delete=django.db.models.deletion.CASCADE, to='tenants.financialinstitution', verbose_name='Institución')),
                ('active_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to='loans.activecredit', verbose_name='Crédito Activo')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_requests', to='clients.client', verbose_name='Cliente')),
                ('request_type', models.CharField(choices=[('GRACE_PERIOD', 'Período de Gracia'), ('RESTRUCTURING', 'Reestructuración')], max_length=20, verbose_name='Tipo de Solicitud')),
                ('reason_category', models.CharField(choices=[('income_reduction', 'Disminución temporal de ingresos'), ('illness', 'Enfermedad'), ('job_loss', 'Pérdida de empleo'), ('family_emergency', 'Emergencia familiar'), ('economic_hardship', 'Dificultad económica temporal'), ('other', 'Otro')], max_length=30, verbose_name='Motivo Principal')),
                ('description', models.TextField(verbose_name='Descripción Detallada')),
                ('requested_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Meses Solicitados', help_text='Cantidad de meses solicitados para gracia o nuevo plazo')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de Contacto')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de revisión'), ('UNDER_REVIEW', 'En revisión'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada'), ('CANCELLED', 'Cancelada')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_support_requests', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('bank_response', models.TextField(blank=True, verbose_name='Respuesta del Banco')),
                ('approved_terms_snapshot', models.JSONField(blank=True, null=True, verbose_name='Snapshot de Términos Aprobados', help_text='Condiciones aprobadas (solo cuando status=APPROVED)')),
                ('requires_more_info', models.BooleanField(default=False, verbose_name='Requiere Más Información')),
                ('requested_info', models.TextField(blank=True, verbose_name='Información Solicitada')),
            ],
            options={
                'verbose_name': 'Solicitud de Apoyo de Pago',
                'verbose_name_plural': 'Solicitudes de Apoyo de Pago',
                'db_table': 'credit_support_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='creditsupportrequest',
            index=models.Index(fields=['active_credit', '-created_at'], name='credit_supp_active__idx'),
        ),
        migrations.AddIndex(
            model_name='creditsupportrequest',
            index=models.Index(fields=['client', '-created_at'], name='credit_supp_client__idx'),
        ),
        migrations.AddIndex(
            model_name='creditsupportrequest',
            index=models.Index(fields=['status'], name='credit_supp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='creditsupportrequest',
            index=models.Index(fields=['request_type', 'status'], name='credit_supp_type_st_idx'),
        ),
    ]
