# Generated by Django 6.0 on 2026-04-11 14:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Ej: Básico, Profesional, Empresarial', max_length=100, unique=True, verbose_name='Nombre del Plan')),
                ('slug', models.SlugField(help_text='Identificador único en URL', max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(help_text='Descripción detallada del plan', verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio del plan en Bolivianos', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio (Bs)')),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Mensual'), ('QUARTERLY', 'Trimestral'), ('ANNUAL', 'Anual')], default='MONTHLY', max_length=10, verbose_name='Ciclo de Facturación')),
                ('trial_days', models.IntegerField(default=30, help_text='Días de prueba gratuita', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Días de Prueba')),
                ('setup_fee', models.DecimalField(decimal_places=2, default=0, help_text='Costo único de configuración inicial', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo de Configuración (Bs)')),
                ('max_users', models.IntegerField(default=10, help_text='Número máximo de usuarios del sistema', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Máximo de Usuarios')),
                ('max_branches', models.IntegerField(default=1, help_text='Número máximo de sucursales', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Máximo de Sucursales')),
                ('max_products', models.IntegerField(default=5, help_text='Número máximo de productos crediticios', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Máximo de Productos')),
                ('max_loans_per_month', models.IntegerField(default=100, help_text='Número máximo de solicitudes de crédito por mes', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Máximo de Créditos por Mes')),
                ('max_storage_gb', models.IntegerField(default=10, help_text='Espacio de almacenamiento para documentos', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Almacenamiento Máximo (GB)')),
                ('has_ai_scoring', models.BooleanField(default=False, help_text='Evaluación crediticia con inteligencia artificial', verbose_name='Scoring con IA')),
                ('has_workflows', models.BooleanField(default=False, help_text='Flujos de trabajo personalizables', verbose_name='Workflows Configurables')),
                ('has_reporting', models.BooleanField(default=True, help_text='Dashboards y reportes avanzados', verbose_name='Reportes y Analítica')),
                ('has_mobile_app', models.BooleanField(default=True, help_text='Acceso a aplicación móvil para prestatarios', verbose_name='App Móvil')),
                ('has_api_access', models.BooleanField(default=False, help_text='Acceso a API REST para integraciones', verbose_name='Acceso API')),
                ('has_white_label', models.BooleanField(default=False, help_text='Personalización de marca', verbose_name='White Label')),
                ('has_priority_support', models.BooleanField(default=False, help_text='Soporte técnico prioritario', verbose_name='Soporte Prioritario')),
                ('has_custom_integrations', models.BooleanField(default=False, help_text='Integraciones con sistemas externos', verbose_name='Integraciones Personalizadas')),
                ('is_active', models.BooleanField(default=True, help_text='Plan disponible para contratación', verbose_name='Activo')),
                ('is_featured', models.BooleanField(default=False, help_text='Mostrar como plan recomendado', verbose_name='Destacado')),
                ('display_order', models.IntegerField(default=0, help_text='Orden en que se muestra (menor primero)', verbose_name='Orden de Visualización')),
                ('features_list', models.JSONField(blank=True, default=list, help_text='Lista de características para mostrar en UI', verbose_name='Lista de Características')),
            ],
            options={
                'verbose_name': 'Plan de Suscripción',
                'verbose_name_plural': 'Planes de Suscripción',
                'ordering': ['display_order', 'price'],
                'indexes': [models.Index(fields=['is_active'], name='saas_subscr_is_acti_dfd45a_idx'), models.Index(fields=['slug'], name='saas_subscr_slug_11d1e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('TRIAL', 'Período de Prueba'), ('ACTIVE', 'Activa'), ('SUSPENDED', 'Suspendida'), ('CANCELLED', 'Cancelada'), ('EXPIRED', 'Expirada')], default='TRIAL', max_length=10, verbose_name='Estado')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, help_text='Fecha de finalización de la suscripción', null=True, verbose_name='Fecha de Fin')),
                ('trial_end_date', models.DateField(blank=True, null=True, verbose_name='Fin del Período de Prueba')),
                ('next_billing_date', models.DateField(blank=True, null=True, verbose_name='Próxima Fecha de Facturación')),
                ('last_billing_date', models.DateField(blank=True, null=True, verbose_name='Última Fecha de Facturación')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagado'), ('OVERDUE', 'Vencido'), ('FAILED', 'Fallido')], default='PENDING', max_length=10, verbose_name='Estado de Pago')),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto Adeudado (Bs)')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, help_text='Total acumulado pagado', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Pagado (Bs)')),
                ('current_users', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Usuarios Actuales')),
                ('current_branches', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sucursales Actuales')),
                ('current_products', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Productos Actuales')),
                ('current_month_loans', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Créditos del Mes Actual')),
                ('current_storage_gb', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Almacenamiento Usado (GB)')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='Motivo de Cancelación')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas Internas')),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.financialinstitution', verbose_name='Institución Financiera')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='saas.subscriptionplan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='saas_subscr_status_0d9c3b_idx'), models.Index(fields=['payment_status'], name='saas_subscr_payment_6b35e8_idx'), models.Index(fields=['next_billing_date'], name='saas_subscr_next_bi_eba28f_idx')],
            },
        ),
    ]
