# Generated by Django 6.0.4 on 2026-05-06 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_create_file_resource_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backup_type', models.CharField(choices=[('full', 'Completo'), ('metadata_only', 'Solo Metadatos'), ('storage_only', 'Solo Archivos')], default='full', max_length=20, verbose_name='Tipo de Backup')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Ejecutando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('expired', 'Expirado')], db_index=True, default='pending', max_length=20, verbose_name='Estado')),
                ('backup_path', models.CharField(blank=True, help_text='Ruta completa del archivo en Supabase Storage', max_length=500, null=True, verbose_name='Ruta en Storage')),
                ('manifest_path', models.CharField(blank=True, help_text='Ruta del archivo manifest.json', max_length=500, null=True, verbose_name='Ruta del Manifest')),
                ('record_count', models.JSONField(blank=True, default=dict, help_text='Diccionario con cantidad de registros por tabla', verbose_name='Conteo de Registros')),
                ('file_count', models.PositiveIntegerField(default=0, verbose_name='Cantidad de Archivos')),
                ('total_size_bytes', models.BigIntegerField(default=0, verbose_name='Tamaño Total (bytes)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha después de la cual el backup será eliminado', null=True, verbose_name='Fecha de Expiración')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
                ('checksum', models.CharField(blank=True, help_text='Hash SHA-256 del archivo de backup', max_length=64, null=True, verbose_name='Checksum SHA-256')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el backup', verbose_name='Notas')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_backups', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='tenants.financialinstitution', verbose_name='Institución Financiera')),
            ],
            options={
                'verbose_name': 'Backup de Tenant',
                'verbose_name_plural': 'Backups de Tenants',
                'db_table': 'tenant_backups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schema_version', models.CharField(default='1.0', help_text='Versión del formato de backup', max_length=20, verbose_name='Versión del Esquema')),
                ('included_tables', models.JSONField(blank=True, default=list, help_text='Lista de nombres de tablas incluidas en el backup', verbose_name='Tablas Incluidas')),
                ('record_counts', models.JSONField(blank=True, default=dict, help_text='Diccionario con cantidad de registros por tabla', verbose_name='Conteo de Registros')),
                ('storage_paths', models.JSONField(blank=True, default=dict, help_text='Diccionario con rutas de archivos en Storage', verbose_name='Rutas de Storage')),
                ('file_list', models.JSONField(blank=True, default=list, help_text='Lista de archivos físicos incluidos', verbose_name='Lista de Archivos')),
                ('checksums', models.JSONField(blank=True, default=dict, help_text='Diccionario con checksums SHA-256 por archivo', verbose_name='Checksums')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional sobre el backup', verbose_name='Metadata Adicional')),
                ('backup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manifest', to='backups.tenantbackup', verbose_name='Backup')),
            ],
            options={
                'verbose_name': 'Manifest de Backup',
                'verbose_name_plural': 'Manifests de Backups',
                'db_table': 'backup_manifests',
            },
        ),
        migrations.CreateModel(
            name='BackupAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('backup_requested', 'Backup Solicitado'), ('backup_started', 'Backup Iniciado'), ('backup_completed', 'Backup Completado'), ('backup_failed', 'Backup Fallido'), ('backup_downloaded', 'Backup Descargado'), ('backup_deleted', 'Backup Eliminado'), ('backup_expired', 'Backup Expirado'), ('restore_started', 'Restauración Iniciada'), ('restore_completed', 'Restauración Completada'), ('restore_failed', 'Restauración Fallida'), ('backup_access_denied', 'Acceso Denegado'), ('backup_unauthorized_attempt', 'Intento No Autorizado')], db_index=True, max_length=30, verbose_name='Acción')),
                ('severity', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error'), ('critical', 'Crítico')], default='info', max_length=20, verbose_name='Severidad')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional sobre la acción', verbose_name='Datos Adicionales')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_audit_actions', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_audit_logs', to='tenants.financialinstitution', verbose_name='Institución Financiera')),
                ('backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='backups.tenantbackup', verbose_name='Backup')),
            ],
            options={
                'verbose_name': 'Log de Auditoría de Backup',
                'verbose_name_plural': 'Logs de Auditoría de Backups',
                'db_table': 'backup_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tenantbackup',
            index=models.Index(fields=['tenant', '-created_at'], name='tenant_back_tenant__69aebc_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantbackup',
            index=models.Index(fields=['status'], name='tenant_back_status_b81015_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantbackup',
            index=models.Index(fields=['expires_at'], name='tenant_back_expires_0622b2_idx'),
        ),
        migrations.AddIndex(
            model_name='backupauditlog',
            index=models.Index(fields=['tenant', '-created_at'], name='backup_audi_tenant__9ae994_idx'),
        ),
        migrations.AddIndex(
            model_name='backupauditlog',
            index=models.Index(fields=['backup'], name='backup_audi_backup__cb55bc_idx'),
        ),
        migrations.AddIndex(
            model_name='backupauditlog',
            index=models.Index(fields=['action'], name='backup_audi_action_153bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='backupauditlog',
            index=models.Index(fields=['severity'], name='backup_audi_severit_a861d3_idx'),
        ),
    ]
