# Generated by Django 6.0.4 on 2026-06-20 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_create_file_resource_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration_type', models.CharField(choices=[('STRIPE', 'Stripe - Pagos'), ('DIDIT', 'Didit - Verificación Identidad'), ('BREVO', 'Brevo - Email'), ('SUPABASE', 'Supabase - Storage'), ('GROQ', 'GroqCloud - IA'), ('CREDIT_BUREAU', 'Bureau de Crédito'), ('PAYMENT_GATEWAY', 'Gateway de Pagos'), ('NOTIFICATION', 'Servicio de Notificaciones'), ('BI_ANALYTICS', 'BI/Analytics'), ('ACCOUNTING', 'Sistema Contable'), ('DIGITAL_SIGNATURE', 'Firma Digital'), ('GOVERNMENT_API', 'API Gubernamental')], max_length=50, verbose_name='Tipo de Integración')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Integración')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('ERROR', 'Error'), ('TESTING', 'En Prueba')], default='ACTIVE', max_length=20, verbose_name='Estado')),
                ('configuration', models.JSONField(default=dict, help_text='API keys, endpoints, y otros parámetros de configuración', verbose_name='Configuración')),
                ('webhook_url', models.URLField(blank=True, help_text='URL para recibir notificaciones del servicio externo', verbose_name='URL de Webhook')),
                ('webhook_secret', models.CharField(blank=True, max_length=255, verbose_name='Secreto de Webhook')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronización')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='Último Éxito')),
                ('last_error_at', models.DateTimeField(blank=True, null=True, verbose_name='Último Error')),
                ('last_error_message', models.TextField(blank=True, verbose_name='Último Mensaje de Error')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='Contador de Errores')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='Contador de Éxitos')),
                ('is_default', models.BooleanField(default=False, help_text='Si es True, se usa como integración principal para este tipo', verbose_name='Integración por Defecto')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('institution', models.ForeignKey(help_text='Institución financiera a la que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.financialinstitution')),
            ],
            options={
                'verbose_name': 'Integración Externa',
                'verbose_name_plural': 'Integraciones Externas',
                'ordering': ['-is_default', 'integration_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('PAYMENT_PROCESSED', 'Pago Procesado'), ('IDENTITY_VERIFIED', 'Identidad Verificada'), ('EMAIL_SENT', 'Email Enviado'), ('FILE_UPLOADED', 'Archivo Subido'), ('AI_REQUEST', 'Solicitud IA'), ('CREDIT_CHECK', 'Consulta Crédito'), ('WEBHOOK_RECEIVED', 'Webhook Recibido'), ('SYNC', 'Sincronización'), ('TEST_CONNECTION', 'Prueba de Conexión'), ('OTHER', 'Otro')], max_length=50, verbose_name='Acción')),
                ('status', models.CharField(choices=[('SUCCESS', 'Éxito'), ('FAILED', 'Fallo'), ('PENDING', 'Pendiente'), ('TIMEOUT', 'Timeout')], max_length=20, verbose_name='Estado')),
                ('request_data', models.JSONField(blank=True, default=dict, verbose_name='Datos de Solicitud')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='Datos de Respuesta')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('error_code', models.CharField(blank=True, max_length=50, verbose_name='Código de Error')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración (ms)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos Adicionales')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integrations.externalintegration', verbose_name='Integración')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Integración',
                'verbose_name_plural': 'Logs de Integraciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='externalintegration',
            index=models.Index(fields=['institution', 'integration_type'], name='integration_institu_78ba64_idx'),
        ),
        migrations.AddIndex(
            model_name='externalintegration',
            index=models.Index(fields=['institution', 'status'], name='integration_institu_dc9cd3_idx'),
        ),
        migrations.AddIndex(
            model_name='externalintegration',
            index=models.Index(fields=['integration_type'], name='integration_integra_78692d_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalintegration',
            constraint=models.UniqueConstraint(fields=('institution', 'integration_type', 'name'), name='unique_integration_name_per_type'),
        ),
        migrations.AddIndex(
            model_name='integrationlog',
            index=models.Index(fields=['integration', 'created_at'], name='integration_integra_8c5170_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationlog',
            index=models.Index(fields=['integration', 'status'], name='integration_integra_50cd4b_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationlog',
            index=models.Index(fields=['action'], name='integration_action_dbdebc_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationlog',
            index=models.Index(fields=['created_at'], name='integration_created_6943ba_idx'),
        ),
    ]
